-- v0.6.4 multi-source content audit registry alignment
insert into schema_meta(key,value,updated_at) values ('app_version','0.6.4',now()),('content_audit_at','2026-08-19',now()) on conflict(key) do update set value=excluded.value,updated_at=excluded.updated_at;

update sources set metadata=metadata || '{"purpose":"Near-live scores/game state and basic fallback only; not authoritative roster or injury data","status":"Ready as isolated fallback"}'::jsonb,updated_at=now() where slug='espn';
update sources set enabled=false,updated_at=now() where slug in ('threads','youtube') and metadata->>'status' like 'Needs%';

insert into sources(slug,name,tier,category,base_url,enabled,capabilities,metadata) values
('nfl-official','NFL.com','official','league','https://www.nfl.com',true,array['schedule','roster','stats','news'],jsonb_build_object('authority_rank',2,'cost','Free / no payment method','method','Official league web','status','Ready for cross-check','cadence','Minutes-hours','purpose','Official league cross-check for schedule, roster, stats and league context')),
('pfhof','Pro Football Hall of Fame','official','history','https://www.profootballhof.com',true,array['history','records'],jsonb_build_object('authority_rank',2,'cost','Free','method','Public web','status','Ready for historical cross-check','cadence','Reference','purpose','Authoritative franchise grant dates, championships, retired numbers and historical records')),
('pro-football-reference','Pro Football Reference','media','stats','https://www.pro-football-reference.com',true,array['history','stats','schedule','roster'],jsonb_build_object('authority_rank',3,'cost','Free public reference','method','Public web','status','Secondary cross-check only','cadence','Daily/reference','purpose','Historical and statistical cross-check; official Titans/NFL sources override conflicts')),
('wikipedia','Wikipedia','media','history','https://en.wikipedia.org/wiki/Tennessee_Titans',true,array['history','context'],jsonb_build_object('authority_rank',4,'cost','Free','method','Public encyclopedia','status','Secondary cross-check only','cadence','Reference','purpose','Broad franchise context; never primary for current roster, schedule, injuries or transactions')),
('sportslogos','SportsLogos.net','media','brand','https://www.sportslogos.net',true,array['logos','uniform-history'],jsonb_build_object('authority_rank',3,'cost','Free public reference','method','Public web/editorial archive','status','Secondary visual cross-check','cadence','Reference','purpose','Logo/uniform era cross-check; official Titans brand/history pages override conflicts'))
on conflict(slug) do update set name=excluded.name,tier=excluded.tier,category=excluded.category,base_url=excluded.base_url,enabled=excluded.enabled,capabilities=excluded.capabilities,metadata=excluded.metadata,updated_at=now();
