const ahRoute=()=>location.hash.replace(/^#/,'').split('?')[0]||'home';
const ahEsc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ahNum=(v,d=3)=>v==null||!Number.isFinite(Number(v))?'—':Number(v).toFixed(d);
const ahSigned=(v,d=3)=>v==null||!Number.isFinite(Number(v))?'—':`${Number(v)>0?'+':''}${Number(v).toFixed(d)}`;
const ahRank=(rank,total)=>rank?`#${rank}${total?` of ${total}`:''}`:'Rank unavailable';
const ahSafeUrl=value=>{try{const u=new URL(String(value||''),location.origin);return ['http:','https:'].includes(u.protocol)?u.href:''}catch{return''}};
const ahStamp=v=>{const d=new Date(v);return Number.isNaN(d.getTime())?'Update time unavailable':new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}).format(d)};
let ahSerial=0;

function metricCard(label,value,detail,help){return `<article class="ah-metric"><small>${ahEsc(label)}</small><strong>${ahEsc(value)}</strong><span>${ahEsc(detail)}</span><p>${ahEsc(help)}</p></article>`}
function sourceList(rows){return `<div class="ah-sources">${(rows||[]).map(s=>{const url=ahSafeUrl(s.url),body=`<b>${ahEsc(s.label)}</b>${ahEsc(s.role)}`;return url?`<a href="${ahEsc(url)}" target="_blank" rel="noopener noreferrer">${body}<em>Source ↗</em></a>`:`<span>${body}</span>`}).join('')}</div>`}
function teamStatLine(stats={}){const keys=[['passing_yards','Pass yds'],['rushing_yards','Rush yds'],['passing_tds','Pass TD'],['rushing_tds','Rush TD'],['passing_interceptions','INT'],['sacks_suffered','Sacks']];const items=keys.filter(([k])=>stats[k]!=null);return items.length?`<div class="ah-box-stats">${items.map(([k,l])=>`<span><small>${l}</small><b>${ahEsc(stats[k])}</b></span>`).join('')}</div>`:''}
function weekRows(weeks=[]){return weeks.map(w=>`<div class="ah-week-row"><div><b>W${ahEsc(w.week)}</b><span>${w.homeAway==='home'?'vs':'at'} ${ahEsc(w.opponent||'—')}</span></div><span><small>Off EPA/play</small><b>${ahSigned(w.offensiveEpaPerPlay)}</b></span><span><small>Def EPA/play allowed</small><b>${ahSigned(w.defensiveEpaPerPlayAllowed)}</b></span><span><small>Pace</small><b>${w.paceSecondsPerPlay==null?'—':`${ahNum(w.paceSecondsPerPlay,1)}s`}</b></span><span><small>Rest</small><b>${w.restDays==null?'—':`${w.restDays}d`}</b></span>${teamStatLine(w.teamStats)}</div>`).join('')}
function downRows(rows=[]){return `<div class="ah-down-grid">${rows.map(r=>`<article><small>${ahEsc(r.down)}${r.down===1?'st':r.down===2?'nd':r.down===3?'rd':'th'} down</small><strong>${ahSigned(r.offensiveEpaPerPlay)}</strong><span>Offense · ${r.offensePlays||0} plays</span><strong class="def">${ahSigned(r.defensiveEpaPerPlayAllowed)}</strong><span>Defense allowed · ${r.defensePlays||0} plays</span></article>`).join('')}</div>`}
function personnelRows(rows=[]){return `<div class="ah-personnel-grid">${['Offense','Defense'].map(side=>`<section><h4>${side} personnel</h4>${rows.filter(r=>r.side===side).slice(0,6).map(r=>`<div><span>${ahEsc(r.package||'Unknown package')}</span><b>${r.plays||0} plays</b><em>${ahSigned(r.epaPerPlay)} EPA/play${side==='Defense'?' allowed':''}</em></div>`).join('')||'<p>Personnel data is not available for this season yet.</p>'}</section>`).join('')}</div>`}
function playPackage(p){return p.side==='offense'?(p.offensePersonnel||'—'):(p.defensePersonnel||'—')}
function fieldPosition(p){if(p.yardline)return p.yardline;if(p.yardline100!=null)return `${ahNum(p.yardline100,0)} yd to goal`;return'—'}
function timeLabel(p){return p.quarter?`Q${p.quarter} ${p.clock||''}`.trim():(p.gameSecondsRemaining!=null?`${Math.floor(p.gameSecondsRemaining/60)}:${String(p.gameSecondsRemaining%60).padStart(2,'0')}`:'—')}
function teamEpa(p){if(p.epa==null)return null;return p.side==='defense'?-Number(p.epa):Number(p.epa)}
function playRows(plays=[],state){const filtered=plays.filter(p=>(state.side==='all'||p.side===state.side)&&(state.down==='all'||String(p.down)===state.down));return `<div class="ah-play-count">${filtered.length} of ${plays.length} recent Titans-involved plays shown</div><div class="ah-play-list">${filtered.slice(0,60).map(p=>`<article class="ah-play ${p.side}"><header><span>W${ahEsc(p.week)} · ${p.side==='offense'?'TEN offense':'TEN defense'}</span><b>${ahEsc(timeLabel(p))}</b></header><div class="ah-situation"><span><small>Down & distance</small><b>${p.down?`${p.down} & ${p.distance??'—'}`:'—'}</b></span><span><small>Field position</small><b>${ahEsc(fieldPosition(p))}</b></span><span><small>Score diff</small><b>${ahSigned(p.scoreDifferential,0)}</b></span><span><small>Time remaining</small><b>${ahEsc(timeLabel(p))}</b></span><span><small>Personnel</small><b>${ahEsc(playPackage(p))}</b></span><span><small>Formation</small><b>${ahEsc(p.offenseFormation||'—')}</b></span><span><small>TEN EPA</small><b>${ahSigned(teamEpa(p))}</b></span></div><p>${ahEsc(p.description||'Play description unavailable')}</p></article>`).join('')||'<div class="ah-empty">No plays match these filters.</div>'}</div>`}
function playControls(state){return `<div class="ah-play-controls"><label>Side<select id="ah-side"><option value="all" ${state.side==='all'?'selected':''}>All Titans plays</option><option value="offense" ${state.side==='offense'?'selected':''}>Titans offense</option><option value="defense" ${state.side==='defense'?'selected':''}>Titans defense</option></select></label><label>Down<select id="ah-down"><option value="all">All downs</option>${[1,2,3,4].map(n=>`<option value="${n}" ${state.down===String(n)?'selected':''}>${n}</option>`).join('')}</select></label></div>`}
function wirePlayFilters(section,data,state){section.querySelector('#ah-side')?.addEventListener('change',e=>{state.side=e.target.value;section.querySelector('#ah-play-wrap').innerHTML=playRows(data.recentPlays||[],state)});section.querySelector('#ah-down')?.addEventListener('change',e=>{state.down=e.target.value;section.querySelector('#ah-play-wrap').innerHTML=playRows(data.recentPlays||[],state)})}

function renderAnalytics(hub,data){
  hub.querySelector('.advanced-analytics-hub')?.remove();
  const section=document.createElement('section');section.className='advanced-analytics-hub';
  section.dataset.requestedSeason=String(data.requestedSeason??'');section.dataset.dataSeason=String(data.dataSeason??'');section.dataset.seasonFallback=String(Boolean(data.seasonFallback));
  const summary=data.summary,state={side:'all',down:'all'};
  if(!summary){section.innerHTML=`<div class="ah-head"><div><small>nflverse analytics</small><h2>Advanced team + play-by-play lab</h2><p>nflreadpy is connected and waiting for the first completed regular-season play-by-play import.</p></div></div><div class="ah-empty">No completed regular-season analytics are stored yet. The current Titans roster and preseason stats remain available above.</div>${sourceList(data.sources)}`;hub.querySelector('.ps-summary')?.insertAdjacentElement('afterend',section);return;}
  const seasonFallback=Boolean(data.seasonFallback),fallback=seasonFallback?`Showing ${data.dataSeason} regular-season analytics because ${data.requestedSeason} regular-season play-by-play is not available yet.`:`${data.dataSeason} regular-season analytics.`;
  const title=seasonFallback?`${data.dataSeason} advanced analytics baseline`:'Advanced team + play-by-play lab';
  const seasonContext=seasonFallback?`<aside class="ah-season-context" role="note" aria-label="Analytics season context"><strong>${ahEsc(data.dataSeason)} regular-season baseline</strong><span>Not ${ahEsc(data.requestedSeason)} performance. These metrics stay historical until completed ${ahEsc(data.requestedSeason)} regular-season play-by-play is available.</span></aside>`:'';
  section.innerHTML=`<div class="ah-head"><div><small>nflverse / nflfastR · nflreadpy · ${ahEsc(data.dataSeason)} REGULAR SEASON</small><h2>${ahEsc(title)}</h2><p>${ahEsc(fallback)} Updated ${ahEsc(ahStamp(data.coverage?.analytics_last_ingest_at||summary.calculatedAt||data.fetchedAt))}.</p></div><span>${data.coverage?.plays||0} plays in warehouse</span></div>${seasonContext}<div class="ah-metrics">${metricCard('Offensive EPA / play',ahSigned(summary.offensiveEpaPerPlay),ahRank(summary.offenseRank,summary.teamCount),'Higher is better. Designed pass/rush plays with EPA.')}${metricCard('Defensive EPA / play allowed',ahSigned(summary.defensiveEpaPerPlayAllowed),ahRank(summary.defenseRank,summary.teamCount),'Lower is better. Opponent EPA while Tennessee is on defense.')}${metricCard('Pace',summary.paceSecondsPerPlay==null?'—':`${ahNum(summary.paceSecondsPerPlay,1)} sec/play`,ahRank(summary.paceRank,summary.teamCount),'Observed game-clock seconds between Tennessee offensive plays; lower is faster.')}${metricCard('Rest days',summary.latestRestDays==null?'—':`${summary.latestRestDays} days`,`Latest loaded week: ${summary.latestWeek||'—'}`,'Uses nflverse schedule home_rest / away_rest fields.')}</div><details class="ah-details" open><summary>Weekly team trend</summary><div class="ah-week-table">${weekRows(data.weeks||[])||'<div class="ah-empty">No weekly rows loaded.</div>'}</div></details><details class="ah-details"><summary>EPA by down</summary>${downRows(data.byDown||[])}</details><details class="ah-details"><summary>Personnel packages</summary>${personnelRows(data.personnel||[])}</details><div class="ah-play-head"><div><small>Situation explorer · ${ahEsc(data.dataSeason)} regular season</small><h3>Recent play-by-play</h3><p>Down & distance, field position, Titans score differential, time remaining, personnel, formation, and EPA on every stored play.</p></div>${playControls(state)}</div><div id="ah-play-wrap">${playRows(data.recentPlays||[],state)}</div><p class="ah-method">TEN EPA is shown from Tennessee's perspective: offensive EPA is unchanged; opponent EPA is inverted on defensive plays. Personnel is joined from nflverse participation data when available, so the current season may lag until that dataset is released.</p>${sourceList(data.sources)}`;
  hub.querySelector('.ps-summary')?.insertAdjacentElement('afterend',section);wirePlayFilters(section,data,state);
}

async function loadAdvancedAnalytics(){
  if(ahRoute()!=='stats')return;
  const app=document.querySelector('#app'),hub=app?.querySelector('.preseason-stats-hub');
  if(!app||!hub||hub.querySelector('.advanced-analytics-hub'))return;
  const requestId=++ahSerial,placeholder=document.createElement('section');placeholder.className='advanced-analytics-hub';placeholder.dataset.loading='true';placeholder.innerHTML='<div class="ah-loading">Loading nflverse EPA, pace, rest and play-by-play…</div>';hub.querySelector('.ps-summary')?.insertAdjacentElement('afterend',placeholder);
  try{
    const response=await fetch('/api/advanced-analytics?season=2026&team=TEN',{headers:{Accept:'application/json'},cache:'no-store'}),data=await response.json();
    if(requestId!==ahSerial||ahRoute()!=='stats')return;
    if(!response.ok||!data.ok)throw new Error(data.error||'Advanced analytics unavailable');
    placeholder.remove();renderAnalytics(hub,data);
  }catch(error){
    if(requestId!==ahSerial||ahRoute()!=='stats')return;
    placeholder.innerHTML=`<div class="ah-error"><strong>Advanced analytics could not load.</strong><span>${ahEsc(error.message||'Try again shortly.')}</span><button type="button" class="button primary" id="ah-retry">Try again</button></div>`;delete placeholder.dataset.loading;placeholder.querySelector('#ah-retry')?.addEventListener('click',()=>{placeholder.remove();queueMicrotask(loadAdvancedAnalytics)});
  }
}

const ahApp=document.querySelector('#app');if(ahApp)new MutationObserver(()=>queueMicrotask(loadAdvancedAnalytics)).observe(ahApp,{childList:true});
addEventListener('hashchange',()=>{ahSerial++;queueMicrotask(loadAdvancedAnalytics)});
queueMicrotask(loadAdvancedAnalytics);
