import { team, games as seedGames, roster as seedRoster, feed as seedFeed, sources as seedSources } from './src/data.mjs';
import { filterFeed, relativeTime, gameStatus, normalizeEspnEvent, mergeLiveGames } from './src/core.mjs';
import { formatAmerican, americanToImplied } from './src/odds.mjs';

const $=s=>document.querySelector(s), app=$('#app'), toast=$('#toast'), sidebar=$('#sidebar');
let games=[...seedGames],roster=[...seedRoster],feed=[...seedFeed],sources=[...seedSources],transactions=[],markets=[],futures=[],mode='fallback',db={connected:false,schemaVersion:null};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const route=()=>location.hash.replace(/^#/,'').split('?')[0]||'home';
const params=()=>new URLSearchParams(location.hash.split('?')[1]||'');
const date=(v,o={})=>v?new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',...o}).format(new Date(v)):'TBD';
const gameTime=v=>v?new Intl.DateTimeFormat('en-US',{weekday:'short',month:'short',day:'numeric',hour:'numeric',minute:'2-digit',timeZone:'America/Chicago'}).format(new Date(v)):'TBD';
const safeUrl=v=>{try{const u=new URL(String(v||''),location.origin);return ['http:','https:'].includes(u.protocol)?u.href:String(v||'#').startsWith('#')?String(v):'#'}catch{return '#'}};
function say(m){toast.textContent=m;toast.classList.add('show');clearTimeout(say.t);say.t=setTimeout(()=>toast.classList.remove('show'),2200)}
function active(){document.querySelectorAll('[data-route]').forEach(a=>a.classList.toggle('active',a.dataset.route===route()));sidebar.classList.remove('open')}
function head(k,t,d,a=''){return `<div class="page-head"><div><div class="eyebrow">${k}</div><h1>${t}</h1><p>${d}</p></div>${a}</div>`}
function panel(t,b,s=''){return `<section class="panel"><div class="panel-head"><h2>${t}</h2>${s}</div>${b}</section>`}
function nextGame(){return games.find(g=>new Date(g.date)>new Date()&&g.status!=='final')||games.at(-1)}
function badges(){return `<span class="tag official">${mode==='neon'?'NEON':'VERIFIED FALLBACK'}</span>`}
function metrics(){const finals=games.filter(g=>String(g.week).startsWith('P')&&g.status==='final'),w=finals.filter(g=>+g.score>+g.opponentScore).length,l=finals.filter(g=>+g.score<+g.opponentScore).length,n=nextGame();return `<div class="grid metrics">${[['Preseason',`${w}–${l}`,'Current results'],['Next game',n?.opponentAbbr||'—',n?date(n.date):'TBD'],['Roster indexed',roster.length,db.connected?'Neon snapshot':'Verified subset'],['Data mode',mode==='neon'?'Neon':'Fallback',db.schemaVersion?`Schema ${db.schemaVersion}`:'PWA ready']].map(x=>`<div class="metric"><div class="label">${x[0]}</div><div class="value">${x[1]}</div><div class="delta">${x[2]}</div></div>`).join('')}</div>`}
function matchup(g){if(!g)return '<div class="empty">Schedule unavailable.</div>';const home=g.homeAway==='home';return `<div class="game-hero"><div class="game-meta"><span>${esc(String(g.week).startsWith('P')?'Preseason '+String(g.week).slice(1):'Week '+g.week)}</span>${badges()}</div><div class="matchup"><div><div class="team-token">TEN</div><strong>Tennessee</strong></div><div class="vs">${g.status==='final'?`${esc(g.score)}<br><small>FINAL</small><br>${esc(g.opponentScore)}`:'VS'}</div><div><div class="team-token opponent">${esc(g.opponentAbbr)}</div><strong>${esc(g.opponent)}</strong></div></div><div class="game-footer"><span><strong>${esc(g.venue||'Venue TBD')}</strong><br>${home?'Nashville, TN':'Road game'}</span><span><strong>${gameTime(g.date)}</strong><br>${esc(g.network||'TV TBD')} · ${gameStatus(g)}</span></div></div>`}
function intel(items=feed.slice(0,6)){return `<div class="intel-list">${items.map(i=>`<a class="intel-item" href="${esc(safeUrl(i.url))}" ${safeUrl(i.url).startsWith('http')?'target="_blank" rel="noopener noreferrer"':''}><span class="source-dot ${esc(i.tier)}"></span><div><h3>${esc(i.title)}</h3><p>${esc(i.summary)}</p><div class="tags">${(i.topics||[]).slice(0,3).map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div></div><time>${relativeTime(i.publishedAt)}</time></a>`).join('')}</div>`}
function home(){app.innerHTML=head('Titans Intelligence','Command Center','Games, roster changes, news, analytics, weather and free market data in one mobile-first PWA.',`<span class="live-chip"><i></i>${esc(team.phase)}</span>`)+metrics()+`<div class="grid dashboard-grid">${panel('Next game',matchup(nextGame()),'<a href="#games"><small>Full schedule →</small></a>')}${panel('Latest intel',intel(),'<a href="#feed"><small>View all →</small></a>')}</div><div class="footer-note">Official sources rank above media, reporters and community posts. Free/no-card data sources only.</div>`}
function gamesPage(){app.innerHTML=head('2026 Season','Games & Schedule','Current preseason and regular-season schedule with live scoreboard refresh support.')+`<div class="schedule">${games.map(g=>`<div class="game-row"><div class="week">${esc(String(g.week).startsWith('P')?g.week:'Wk '+g.week)}</div><div class="opponent-line"><div class="mini-token">${esc(g.opponentAbbr)}</div><div><strong>${g.homeAway==='home'?'vs':'at'} ${esc(g.opponent)}</strong><small>${esc(g.venue||'')}</small></div></div><div class="game-date"><strong>${date(g.date,{weekday:'short'})}</strong><small>${gameTime(g.date)}</small></div><div class="score ${g.status==='final'&&+g.score>+g.opponentScore?'result-w':''}">${g.status==='final'?`${esc(g.score)}–${esc(g.opponentScore)}`:gameStatus(g)}</div></div>`).join('')}</div>`}
function rosterPage(){app.innerHTML=head('Personnel','Roster','Search the latest Neon roster snapshot or verified fallback subset.')+`<div class="filterbar"><input id="rs" placeholder="Search roster…"><select id="ru"><option value="all">All units</option><option>Offense</option><option>Defense</option><option>Special Teams</option></select></div><div class="grid roster-grid" id="rg"></div>`;const draw=()=>{const q=$('#rs').value.toLowerCase(),u=$('#ru').value;$('#rg').innerHTML=roster.filter(p=>(u==='all'||p.unit===u)&&`${p.name} ${p.position} ${p.number}`.toLowerCase().includes(q)).map(p=>`<div class="player-card"><div class="jersey">${esc(p.number)}</div><div><h3>${esc(p.name)}</h3><p>${esc(p.position)} · ${esc(p.unit||'')}</p></div><span class="player-tag">${esc(p.tag||p.status||'Active')}</span></div>`).join('')||'<div class="empty">No matching players.</div>'};$('#rs').addEventListener('input',draw);$('#ru').addEventListener('input',draw);draw()}
function transactionsPage(){app.innerHTML=head('Personnel Movement','Transactions','Latest structured Titans roster transactions from Neon.')+panel(`Transactions · ${transactions.length}`,transactions.length?`<div class="transaction-list">${transactions.map(t=>`<div class="transaction-row"><div class="transaction-date"><strong>${date(t.date,{year:'numeric'})}</strong><small>${esc(t.type||'transaction')}</small></div><p>${esc(t.description)}</p></div>`).join('')}</div>`:'<div class="panel-body"><div class="empty">No transaction rows available yet.</div></div>')}
function statsPage(){app.innerHTML=head('Performance','Stats Lab','Warehouse-backed analytics are ready for play-by-play backfill.')+`<div class="grid stat-grid">${[['Games',games.length,'2026 indexed'],['Roster',roster.length,'Current snapshot'],['Markets',markets.length,'Free providers'],['Database',db.connected?'Online':'Fallback',db.schemaVersion||'Not connected']].map(x=>`<div class="stat-card"><small>${x[0]}</small><strong>${x[1]}</strong><p>${x[2]}</p></div>`).join('')}</div>${panel('Analytics warehouse','<div class="panel-body"><div class="notice">EPA, success rate, explosiveness, WPA and play-level splits populate after the nflverse historical importer writes play-by-play rows.</div></div>')}`}
function marketTable(rows){return `<div class="market-table">${rows.map(r=>`<div class="market-row"><div><h3>${esc(r.entityName||r.marketName||'Market')}</h3><p>${esc(r.marketName||r.category||'')}</p></div><div><small>Side</small><strong>${esc(r.side||'—')}</strong></div><div><small>Line</small><strong>${r.line??'—'}</strong></div><div><small>Price</small><strong>${formatAmerican(r.price)}</strong></div><div><small>Implied</small><strong>${americanToImplied(r.price)==null?'—':(americanToImplied(r.price)*100).toFixed(1)+'%'}</strong></div></div>`).join('')}</div>`}
async function refreshOdds(){const b=$('#odds-refresh');if(b){b.disabled=true;b.textContent='Refreshing…'}try{const r=await fetch('/api/odds');const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||'Odds unavailable');markets=d.odds||[];futures=d.futures||[];say(`${d.provider||'Free odds'} · ${markets.length} rows`);marketsPage()}catch(e){say(e.message)}finally{const n=$('#odds-refresh');if(n){n.disabled=false;n.textContent='Refresh odds'}}}
function marketsPage(){app.innerHTML=head('Market Intelligence','Odds & Props','Free/no-card providers only. Informational use; no wagering advice.',`<button class="button primary" id="odds-refresh">Refresh odds</button>`)+`<div class="notice">PropLine is primary; Odds-API.io is secondary fallback. Public requests are cached to protect free daily quotas.</div>${markets.length?marketTable(markets):'<div class="empty">No live market rows loaded yet. Configure the free provider keys in Vercel and refresh.</div>'}`;$('#odds-refresh').addEventListener('click',refreshOdds)}
function feedPage(){app.innerHTML=head('Intelligence','Intel Feed','Official, media, reporter and community updates ranked by trust tier.')+`<div class="filterbar"><input id="fq" placeholder="Search intel…"></div><div id="fl">${intel(feed)}</div>`;$('#fq').addEventListener('input',e=>{$('#fl').innerHTML=intel(filterFeed(feed,{query:e.target.value}))})}
function sourcesPage(){app.innerHTML=head('Data Layer','Sources','Current free/no-card source registry and integration status.')+`<div class="grid source-grid">${sources.map(s=>`<div class="source-card"><div class="source-card-head"><div><h3>${esc(s.name)}</h3><div class="category">${esc(s.category)}</div></div><span class="source-status ${String(s.status).toLowerCase().includes('need')?'needs':'ready'}">${esc(s.status||'Ready')}</span></div><p>${esc(s.purpose||'')}</p><div class="source-meta"><div><small>Method</small><strong>${esc(s.method||'')}</strong></div><div><small>Cost</small><strong>${esc(s.cost||'Free')}</strong></div></div></div>`).join('')}</div>`}
function livePage(){app.innerHTML=head('Game Day','Live Center','Near-live scoreboard adapter with a fast fallback when no Titans game is active.')+`<div class="grid live-board">${panel('Current / next game',matchup(nextGame()))}${panel('Refresh status','<div class="panel-body"><button class="button primary" id="live-refresh">Refresh scoreboard</button><div style="height:12px"></div><div class="notice">ESPN consumer JSON is isolated as an unofficial replaceable adapter.</div></div>')}</div>`;$('#live-refresh').addEventListener('click',refreshLive)}
async function refreshLive(){try{const r=await fetch('/api/espn-scoreboard');const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||'Scoreboard unavailable');const n=(d.payload?.events||[]).map(normalizeEspnEvent).filter(Boolean);if(n.length){games=mergeLiveGames(games,n);say(`Live feed · ${n.length} Titans event${n.length===1?'':'s'}`)}else say('No Titans game on current scoreboard');render()}catch(e){say(e.message)}}
function searchPage(){const q=params().get('q')||'';const ph=roster.filter(p=>`${p.name} ${p.position}`.toLowerCase().includes(q.toLowerCase())),fh=filterFeed(feed,{query:q}),gh=games.filter(g=>`${g.opponent} ${g.opponentAbbr}`.toLowerCase().includes(q.toLowerCase()));app.innerHTML=head('Global Search',`Results for “${esc(q)}”`,'Searches the currently indexed roster, schedule and intel.')+`${ph.length?panel(`Players · ${ph.length}`,`<div class="panel-body"><div class="tags">${ph.map(p=>`<span class="tag">${esc(p.name)} · ${esc(p.position)}</span>`).join('')}</div></div>`):''}${gh.length?panel(`Games · ${gh.length}`,`<div class="panel-body"><div class="tags">${gh.map(g=>`<a class="tag" href="#games">${esc(g.opponent)} · ${date(g.date)}</a>`).join('')}</div></div>`):''}${fh.length?panel(`Intel · ${fh.length}`,intel(fh)):''}${!ph.length&&!gh.length&&!fh.length?'<div class="empty">No matches.</div>':''}`}
const pages={home,games:gamesPage,roster:rosterPage,transactions:transactionsPage,stats:statsPage,markets:marketsPage,feed:feedPage,sources:sourcesPage,live:livePage,search:searchPage};
function render(){active();(pages[route()]||home)()}
async function hydrate(){try{const r=await fetch('/api/data');const d=await r.json();if(!r.ok||!d.ok)throw new Error();if(d.games?.length)games=d.games;if(d.roster?.length)roster=d.roster;if(d.feed?.length)feed=d.feed;if(d.sources?.length)sources=d.sources;if(Array.isArray(d.transactions))transactions=d.transactions;if(Array.isArray(d.markets?.rows))markets=d.markets.rows;if(Array.isArray(d.markets?.futures))futures=d.markets.futures;db={connected:true,schemaVersion:d.meta?.schema_version||null};mode='neon';render()}catch{db.connected=false;mode='fallback'}}
window.addEventListener('hashchange',render);$('#menu-button').addEventListener('click',()=>sidebar.classList.toggle('open'));$('#refresh-button').addEventListener('click',refreshLive);$('#global-search').addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target.value.trim())location.hash=`search?q=${encodeURIComponent(e.target.value.trim())}`});document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#global-search').focus()}});
let installPrompt=null;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('#install-button').hidden=false});$('#install-button').addEventListener('click',async()=>{if(!installPrompt)return;installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;$('#install-button').hidden=true});
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('/sw.js').catch(()=>{}));
render();hydrate();
