const legacyCatalog={timeline:[
{era:'1960–1996',kicker:'Houston Oilers',title:'The derrick era',image:'/assets/archive/oilers-derrick.webp',alt:'Houston Oilers oil derrick logo in light blue, red, and white',copy:'The franchise began in Houston in 1960. The oil derrick and powder-blue identity defined the club for decades before the move to Tennessee.',badge:'Classic franchise mark'},
{era:'1997–1998',kicker:'Tennessee Oilers',title:'The Tennessee transition',image:'/assets/archive/oilers-derrick.webp',alt:'Houston Oilers oil derrick logo used as a franchise-era reference',copy:'The franchise played two seasons as the Tennessee Oilers before adopting the Titans name in 1999. The derrick remained the identifying mark during that transition.',badge:'Franchise transition'},
{era:'1999–2025',kicker:'Tennessee Titans',title:'The fireball generation',image:'/assets/archive/fireball-wordmark.webp',alt:'Tennessee Titans fireball logo beside the classic Titans wordmark',copy:'The Titans name arrived in 1999 with the flaming-T mark and a navy-heavy identity that carried the franchise through more than a quarter century in Tennessee.',badge:'Classic Titans identity'},
{era:'2026–present',kicker:'Tennessee Titans',title:'The Shield',image:'/assets/brand/current-lockup.webp',alt:'Current Tennessee Titans Shield logo and wordmark',copy:'The 2026 identity removes the flames, makes Titans Blue the visual lead, and centers the redesigned Shield and Nashville-inspired 6-String Stripe.',badge:'Current identity'}],archive:[
{image:'/assets/archive/current-shield-primary.webp',title:'The Shield — primary mark',subtitle:'Current identity · 2026–present',kind:'Current identity',alt:'Current Tennessee Titans Shield primary logo'},
{image:'/assets/brand/current-lockup.webp',title:'Current Shield + wordmark',subtitle:'Current identity lockup reference',kind:'Current identity',alt:'Current Tennessee Titans Shield logo with Tennessee Titans wordmark'},
{image:'/assets/archive/logo-transition-shield-fireball.webp',title:'Shield + fireball comparison',subtitle:'Current mark beside the previous Titans mark',kind:'Logo comparison',alt:'Current Titans Shield logo beside the previous Titans fireball logo'},
{image:'/assets/archive/oilers-derrick.webp',title:'Houston Oilers derrick',subtitle:'Classic franchise mark',kind:'Oilers era',alt:'Houston Oilers oil derrick logo'},
{image:'/assets/archive/fireball-wordmark.webp',title:'Fireball + classic wordmark',subtitle:'Titans identity used before 2026',kind:'Fireball era',alt:'Previous Tennessee Titans fireball logo with classic Titans wordmark'},
{image:'/assets/archive/fireball-on-navy.webp',title:'Fireball mark on navy',subtitle:'Previous Titans logo treatment',kind:'Fireball era',alt:'Previous Tennessee Titans fireball logo on a navy background'}]};
function archiveCard(item){return `<figure class="archive-card" data-kind="${item.kind}"><div class="archive-image"><img src="${item.image}" alt="${item.alt}" loading="lazy"></div><figcaption><span class="archive-kind">${item.kind}</span><strong>${item.title}</strong><small>${item.subtitle}</small></figcaption></figure>`}
function timelineCard(item){return `<section class="legacy-era legacy-era-polished"><div class="legacy-era-media"><img src="${item.image}" alt="${item.alt}" loading="lazy"></div><div class="legacy-era-copy"><div class="era-year">${item.era} · ${item.kicker}</div><h3>${item.title}</h3><p>${item.copy}</p><span class="archive-kind">${item.badge}</span></div></section>`}
function applyLegacyPolish(){const legacyPage=document.querySelector('.legacy-page');if(legacyPage&&!legacyPage.dataset.polished){legacyPage.dataset.polished='true';legacyPage.innerHTML=`<div class="archive-note"><strong>Archive labels verified.</strong> The live gallery now uses distinct image files instead of duplicated placeholders, and titles describe what each image actually shows.</div><div class="legacy-timeline-polished">${legacyCatalog.timeline.map(timelineCard).join('')}</div><div class="section-rivet">Visual archive</div><div class="archive-filters" role="group" aria-label="Filter visual archive"><button type="button" class="archive-filter active" data-filter="all">All</button><button type="button" class="archive-filter" data-filter="Current identity">Current</button><button type="button" class="archive-filter" data-filter="Oilers era">Oilers</button><button type="button" class="archive-filter" data-filter="Fireball era">Fireball era</button><button type="button" class="archive-filter" data-filter="Logo comparison">Comparisons</button></div><div class="legacy-gallery archive-gallery-polished">${legacyCatalog.archive.map(archiveCard).join('')}</div><div class="legal-mark-note">Unofficial fan-built archive. Franchise-history context is cross-checked against TennesseeTitans.com. Additional decorative reference art will be added only after it is labeled separately from official/classic marks.</div>`;legacyPage.querySelectorAll('.archive-filter').forEach(button=>button.addEventListener('click',()=>{legacyPage.querySelectorAll('.archive-filter').forEach(x=>x.classList.toggle('active',x===button));const filter=button.dataset.filter;legacyPage.querySelectorAll('.archive-card').forEach(card=>card.hidden=filter!=='all'&&card.dataset.kind!==filter)}))}const callout=document.querySelector('.legacy-callout-art img');if(callout){callout.src='/assets/archive/oilers-derrick.webp';callout.alt='Houston Oilers oil derrick logo'}const hero=document.querySelector('.fan-hero-brand img');if(hero){hero.src='/assets/brand/current-lockup.webp';hero.alt='Current Tennessee Titans Shield logo and wordmark'}const strip=document.querySelector('.legacy-strip');if(strip&&!strip.dataset.polished){strip.dataset.polished='true';strip.innerHTML=[legacyCatalog.archive[2],legacyCatalog.archive[3],legacyCatalog.archive[4],legacyCatalog.archive[0]].map(item=>`<a class="legacy-peek" href="#legacy"><img src="${item.image}" alt="${item.alt}" loading="lazy"><span>${item.title}</span></a>`).join('')}}
const observer=new MutationObserver(applyLegacyPolish),appRoot=document.querySelector('#app');if(appRoot)observer.observe(appRoot,{childList:true,subtree:true});window.addEventListener('hashchange',()=>queueMicrotask(applyLegacyPolish));queueMicrotask(applyLegacyPolish);
