const shEsc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const shRoute=()=>location.hash.replace(/^#/,'').split('?')[0]||'home';
const blank=v=>v==null||v===''||/^(--|—)$/.test(String(v).trim());
const categoryPriority=['Passing','Rushing','Receiving','Defense','Kicking','Punting','Kick Returns','Punt Returns','Special Teams','Fumbles'];
const positionOrder=['QB','RB','WR','TE','C','G','T','DE','DL','DT','LB','CB','DB','S','K','P','LS'];
const positionNames={QB:'Quarterbacks',RB:'Running backs',WR:'Wide receivers',TE:'Tight ends',C:'Centers',G:'Guards',T:'Tackles',DE:'Defensive ends',DL:'Defensive line',DT:'Defensive tackles',LB:'Linebackers',CB:'Cornerbacks',DB:'Defensive backs',S:'Safeties',K:'Kickers',P:'Punters',LS:'Long snappers'};
const teamStatLabels={firstDowns:'First downs',thirdDown:'Third down',totalYards:'Total yards',rushingYards:'Rush yards',netPassingYards:'Net pass yards',penalties:'Penalties',fumbles:'Fumbles',touchdowns:'TDs',fieldGoals:'Field goals',timeOfPossession:'Time of possession'};
const gameDate=v=>{if(!v)return'TBD';const d=new Date(v);return Number.isNaN(d.getTime())?'TBD':new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit',timeZone:'America/Chicago'}).format(d)};
const statsStamp=v=>{if(!v)return'Update time unavailable';const d=new Date(v);return Number.isNaN(d.getTime())?'Update time unavailable':new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}).format(d)};
const shSafeUrl=value=>{try{const url=new URL(String(value||''),location.origin);return ['http:','https:'].includes(url.protocol)?url.href:''}catch{return''}};
let statsRequestSerial=0;
function statLine(stat){const pairs=(stat.fields||[]).filter(x=>!blank(x.value)).slice(0,12);return pairs.length?`<div class="ps-stat-line"><b>${shEsc(stat.category)}</b>${pairs.map(x=>`<span><small>${shEsc(x.label)}</small>${shEsc(x.value)}</span>`).join('')}</div>`:''}
function statsFor(p,view){return view==='season'?(p.seasonStats||[]):(p.stats||[]).filter(x=>String(x.eventId)===String(view))}
function lowBoxPosition(p,coverage){return (coverage?.expectedLowBoxPositions||[]).includes(String(p.position||'').toUpperCase())}
function missingStatsText(p,view,coverage){if(lowBoxPosition(p,coverage))return'Individual box-score production is not normally published for this position. Roster status is still current.';if(view==='season'&&coverage?.completedGamesMissingPlayerStats)return`No player box-score row is loaded yet. Season totals are incomplete because ${coverage.completedGamesMissingPlayerStats} completed preseason game${coverage.completedGamesMissingPlayerStats===1?' is':'s are'} still missing detailed player stats.`;return`No individual box-score statistic was published or loaded ${view==='season'?'in the covered completed preseason games':'for this player in the selected game'}.`}
function playerRow(p,view,coverage){const stats=[...statsFor(p,view)].sort((a,b)=>categoryPriority.indexOf(a.category)-categoryPriority.indexOf(b.category));return `<article class="ps-player"><div class="ps-player-id"><span class="ps-number">${shEsc(p.number||'—')}</span><div><strong>${shEsc(p.name)}</strong><small>${shEsc(p.position||'—')} · ${shEsc(p.status||'Current roster')} · Exp ${shEsc(p.experience||'—')}</small></div></div><div class="ps-lines">${stats.map(statLine).join('')||`<span class="ps-no-stats">${shEsc(missingStatsText(p,view,coverage))}</span>`}</div></article>`}
function teamGrid(stats){const rows=Object.entries(teamStatLabels);return `<div class="ps-team-grid">${rows.map(([k,label])=>{const value=stats?.[k];return `<span class="${blank(value)?'is-unavailable':''}"><small>${shEsc(label)}</small><b>${blank(value)?'Not loaded':shEsc(value)}</b></span>`}).join('')}</div>`}
function sourceLinks(sources){return (sources||[]).map(s=>{const url=shSafeUrl(s.url);return url?`<a href="${shEsc(url)}" target="_blank" rel="noopener noreferrer">${shEsc(s.label)} ↗</a>`:''}).join('')}
function fieldNumber(stats,category,label){const v=stats.find(x=>x.category===category)?.fields?.find(x=>x.label===label)?.value;if(v==null||v==='')return null;const n=Number(String(v).replace(/[^0-9.-]/g,''));return Number.isFinite(n)?n:null}
function leadersFor(players,view,serverLeaders=[]){if(view==='season'&&serverLeaders.length)return serverLeaders;const specs=[['Passing','YDS','Passing yards'],['Rushing','YDS','Rushing yards'],['Receiving','YDS','Receiving yards'],['Defense','COMB','Total tackles'],['Defense','SACK','Sacks'],['Kicking','PTS','Points']];return specs.map(([category,label,title])=>{const ranked=players.map(p=>({name:p.name,number:p.number,position:p.position,value:fieldNumber(statsFor(p,view),category,label)})).filter(x=>x.value!=null).sort((a,b)=>b.value-a.value||a.name.localeCompare(b.name));return ranked.length?{title,...ranked[0]}:{title,value:null}})}
function leadersMarkup(leaders){return `<div class="ps-leaders">${leaders.map(x=>x.value==null?`<article class="is-unavailable"><small>${shEsc(x.title)}</small><strong>Not loaded</strong><span>No verified value in this view</span></article>`:`<article><small>${shEsc(x.title)}</small><strong>${shEsc(x.value)}</strong><span>#${shEsc(x.number||'—')} ${shEsc(x.name)} · ${shEsc(x.position||'')}</span></article>`).join('')}</div>`}
function scheduleMarkup(schedule){return `<div class="ps-schedule">${(schedule||[]).map(g=>`<article class="${g.completed?'complete':'upcoming'}"><small>${shEsc(g.week)} · ${g.completed?'Final':'Scheduled'}${g.completed?` · ${g.statsAvailable?'box stats loaded':'box stats pending'}`:''}</small><strong>${shEsc(g.name)}</strong><span>${shEsc(g.status||gameDate(g.date))}</span><em>${shEsc(g.venue||'')} ${g.network?`· ${shEsc(g.network)}`:''}</em></article>`).join('')}</div>`}
function gameTabs(completed,state){return `<div class="ps-game-tabs" role="tablist" aria-label="Preseason stat view"><button type="button" data-stat-view="season" class="${state.view==='season'?'active':''}">Preseason totals</button>${(completed||[]).map((g,i)=>`<button type="button" data-stat-view="${shEsc(g.id)}" class="${state.view===String(g.id)?'active':''}">P${i+1} · ${shEsc(g.name)}</button>`).join('')}</div>`}
function controls(players,state){const positions=[...new Set(players.map(p=>p.position||'Other'))].sort((a,b)=>{const ai=positionOrder.indexOf(a),bi=positionOrder.indexOf(b);return (ai<0?99:ai)-(bi<0?99:bi)||a.localeCompare(b)});return `<div class="ps-controls"><div class="ps-unit-filters">${['All','Offense','Defense','Special Teams'].map(u=>`<button class="ps-filter ${state.unit===u?'active':''}" data-unit-filter="${u}">${u}</button>`).join('')}</div><div class="ps-control-fields"><select id="ps-position" aria-label="Filter roster by position"><option value="All">All positions</option>${positions.map(p=>`<option value="${shEsc(p)}" ${state.position===p?'selected':''}>${shEsc(p)} · ${shEsc(positionNames[p]||p)}</option>`).join('')}</select><select id="ps-participation" aria-label="Filter roster by preseason stats"><option ${state.participation==='All'?'selected':''}>All</option><option ${state.participation==='With stats'?'selected':''}>With stats</option><option ${state.participation==='No box stats'?'selected':''}>No box stats</option><option ${state.participation==='Reserve/Injured'?'selected':''}>Reserve/Injured</option></select><input id="ps-search" type="search" value="${shEsc(state.q)}" placeholder="Search player or position…" aria-label="Search preseason roster stats"></div></div>`}
function visiblePlayers(players,state){const q=state.q.toLowerCase();return players.filter(p=>{const current=statsFor(p,state.view),has=current.some(s=>(s.fields||[]).some(x=>!blank(x.value)));const unit=state.unit==='All'||p.unit===state.unit,pos=state.position==='All'||p.position===state.position,query=!q||`${p.name} ${p.position} ${p.number}`.toLowerCase().includes(q);let part=true;if(state.participation==='With stats')part=has;if(state.participation==='No box stats')part=!has;if(state.participation==='Reserve/Injured')part=p.status==='Reserve/Injured';return unit&&pos&&query&&part})}
function positionIndex(players,state){const rows=[...new Set(players.map(p=>p.position||'Other'))].sort((a,b)=>{const ai=positionOrder.indexOf(a),bi=positionOrder.indexOf(b);return (ai<0?99:ai)-(bi<0?99:bi)||a.localeCompare(b)});return `<div class="ps-position-index">${rows.map(pos=>{const group=players.filter(p=>p.position===pos),withStats=group.filter(p=>statsFor(p,state.view).length).length;return `<button type="button" data-position-chip="${shEsc(pos)}" class="${state.position===pos?'active':''}"><b>${shEsc(pos)}</b><span>${group.length} roster · ${withStats} with rows</span></button>`}).join('')}</div>`}
function rosterMarkup(players,state,coverage){const visible=visiblePlayers(players,state),groups=new Map();for(const p of visible){const pos=p.position||'Other';if(!groups.has(pos))groups.set(pos,[]);groups.get(pos).push(p)}const ordered=[...groups].sort((a,b)=>{const ai=positionOrder.indexOf(a[0]),bi=positionOrder.indexOf(b[0]);return (ai<0?99:ai)-(bi<0?99:bi)||a[0].localeCompare(b[0])});return `<div class="ps-results-head"><strong>${visible.length} players shown</strong><span>${state.view==='season'?'Covered completed preseason games':'Selected game'} · ${state.position==='All'?'all positions':state.position}</span></div><div class="ps-roster">${ordered.map(([pos,group])=>`<section class="ps-position-group"><header><span>${shEsc(pos)}</span><div><strong>${shEsc(positionNames[pos]||pos)}</strong><small>${group.length} player${group.length===1?'':'s'}</small></div></header><div>${group.map(p=>playerRow(p,state.view,coverage)).join('')}</div></section>`).join('')||'<div class="ps-empty-filter">No players match the current filters.</div>'}</div>`}
function coverageMarkup(coverage){if(!coverage)return'';const complete=coverage.completedGamesMissingPlayerStats===0;return `<section class="ps-coverage ${complete?'complete':'partial'}"><div><small>STAT COVERAGE</small><strong>${coverage.completedGamesWithPlayerStats} of ${coverage.completedGames} completed preseason games have player box-score detail</strong><span>${coverage.playersWithStats} roster players currently have at least one individual stat row.</span></div><div class="ps-coverage-chips"><span><b>${coverage.completedGamesMissingPlayerStats}</b> completed games awaiting player detail</span><span><b>${coverage.playersWithoutStats}</b> roster players without individual rows</span></div></section>`}
function updateDynamic(hub,d,state){hub.querySelector('#ps-game-tabs').innerHTML=gameTabs(d.completedGames,state);hub.querySelector('#ps-team-wrap').innerHTML=teamGrid(state.view==='season'?d.seasonTeamStats:d.teamStatsByGame?.[state.view]);hub.querySelector('#ps-leader-wrap').innerHTML=leadersMarkup(leadersFor(d.players||[],state.view,d.leaders||[]));hub.querySelector('#ps-position-wrap').innerHTML=positionIndex(d.players||[],state);hub.querySelector('#ps-controls-wrap').innerHTML=controls(d.players||[],state);hub.querySelector('#ps-roster-wrap').innerHTML=rosterMarkup(d.players||[],state,d.coverage);wireDynamic(hub,d,state)}
function wireDynamic(hub,d,state){hub.querySelectorAll('[data-stat-view]').forEach(b=>b.addEventListener('click',()=>{state.view=b.dataset.statView;updateDynamic(hub,d,state)}));hub.querySelectorAll('[data-unit-filter]').forEach(b=>b.addEventListener('click',()=>{state.unit=b.dataset.unitFilter;updateDynamic(hub,d,state)}));hub.querySelectorAll('[data-position-chip]').forEach(b=>b.addEventListener('click',()=>{state.position=state.position===b.dataset.positionChip?'All':b.dataset.positionChip;updateDynamic(hub,d,state)}));hub.querySelector('#ps-position')?.addEventListener('change',e=>{state.position=e.target.value;updateDynamic(hub,d,state)});hub.querySelector('#ps-participation')?.addEventListener('change',e=>{state.participation=e.target.value;updateDynamic(hub,d,state)});hub.querySelector('#ps-search')?.addEventListener('input',e=>{state.q=e.target.value;hub.querySelector('#ps-roster-wrap').innerHTML=rosterMarkup(d.players||[],state,d.coverage)})}
async function renderStats(){
  if(shRoute()!=='stats')return;
  const app=document.querySelector('#app');
  if(!app||app.dataset.preseasonHub==='loading'||app.querySelector('.preseason-stats-hub'))return;
  const requestId=++statsRequestSerial;
  app.dataset.preseasonHub='loading';app.setAttribute('aria-busy','true');
  try{
    const r=await fetch('/api/preseason-stats',{headers:{Accept:'application/json'}}),d=await r.json();
    if(requestId!==statsRequestSerial||shRoute()!=='stats')return;
    if(!r.ok||!d.ok)throw new Error(d.error||'Stats unavailable');
    const head=app.querySelector('.page-head');app.innerHTML='';if(head)app.append(head);
    const hub=document.createElement('section');hub.className='preseason-stats-hub';const state={view:'season',unit:'All',position:'All',participation:'All',q:''};hub.innerHTML=`<div class="ps-summary"><div><small>2026 preseason stat book</small><h2>Roster by position + game-by-game preseason stats</h2><p>${shEsc(d.rosterSource||'Roster source')} · ${shEsc(d.statsSource||'Stats source')}</p><small>Updated ${shEsc(statsStamp(d.fetchedAt))}</small></div><div class="ps-counts"><span><b>${d.rosterCount||0}</b> roster players</span><span><b>${d.coverage?.completedGames??(d.completedGames||[]).length}</b> completed games</span><span><b>${(d.positionCounts||[]).length}</b> positions</span></div></div>${coverageMarkup(d.coverage)}${scheduleMarkup(d.preseasonSchedule)}${d.nextGame?`<div class="ps-next"><small>Next preseason game</small><strong>${shEsc(d.nextGame.name)}</strong><span>${shEsc(gameDate(d.nextGame.date))} · ${shEsc(d.nextGame.venue||'Venue TBD')} · ${shEsc(d.nextGame.network||'TV TBD')}</span></div>`:''}<div id="ps-game-tabs"></div><div id="ps-team-wrap"></div><div id="ps-leader-wrap"></div>${(d.diagnostics||[]).length?`<details class="ps-diagnostics"><summary>Data notes</summary><p>${(d.diagnostics||[]).map(shEsc).join(' · ')}</p></details>`:''}<div class="ps-sources">${sourceLinks(d.sources)}</div><div id="ps-position-wrap"></div><div id="ps-controls-wrap"></div><div id="ps-roster-wrap"></div>${(d.otherParticipants||[]).length?`<details class="ps-former"><summary>Preseason participants not matched to the current roster (${d.otherParticipants.length})</summary><div>${d.otherParticipants.map(p=>playerRow(p,state.view,d.coverage)).join('')}</div></details>`:''}<div class="ps-source-note">Stats are preseason only. A real zero stays visible as 0. “Not loaded” means the verified field is absent from the current source. Some positions—especially offensive line—do not normally receive individual traditional box-score production. Coverage above shows when an entire completed game is still missing player-detail rows.</div>`;app.append(hub);updateDynamic(hub,d,state);
  }catch(e){
    if(requestId!==statsRequestSerial||shRoute()!=='stats')return;
    app.insertAdjacentHTML('beforeend',`<div class="ps-error"><strong>Preseason stats could not load.</strong><br>${shEsc(e.message||'Try again shortly.')}<div style="height:12px"></div><button class="button primary" type="button" id="ps-retry">Try again</button></div>`);
    app.querySelector('#ps-retry')?.addEventListener('click',()=>{delete app.dataset.preseasonHub;queueMicrotask(renderStats)});
  }finally{
    if(requestId===statsRequestSerial){delete app.dataset.preseasonHub;app.removeAttribute('aria-busy');}
  }
}
const shRoot=document.querySelector('#app');if(shRoot)new MutationObserver(()=>queueMicrotask(renderStats)).observe(shRoot,{childList:true});
addEventListener('hashchange',()=>{statsRequestSerial++;const app=document.querySelector('#app');if(app){delete app.dataset.preseasonHub;app.removeAttribute('aria-busy');}queueMicrotask(renderStats)});
queueMicrotask(renderStats);