const shEsc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const shRoute=()=>location.hash.replace(/^#/,'').split('?')[0]||'home';
const zero=v=>v==null||v===''||/^(--|—)$/.test(String(v).trim());
const categoryPriority=['Passing','Rushing','Receiving','Defense','Kicking','Punting','Kick Returns','Punt Returns','Special Teams','Fumbles'];
function statLine(stat){const pairs=(stat.fields||[]).filter(x=>!zero(x.value)).slice(0,9);return pairs.length?`<div class="ps-stat-line"><b>${shEsc(stat.category)}</b>${pairs.map(x=>`<span><small>${shEsc(x.label)}</small>${shEsc(x.value)}</span>`).join('')}</div>`:''}
function playerRow(p){const stats=[...(p.stats||[])].sort((a,b)=>categoryPriority.indexOf(a.category)-categoryPriority.indexOf(b.category));return `<article class="ps-player" data-unit="${shEsc(p.unit||'Other')}" data-pos="${shEsc(p.position||'—')}"><div class="ps-player-id"><span class="ps-number">${shEsc(p.number||'—')}</span><div><strong>${shEsc(p.name)}</strong><small>${shEsc(p.position||'—')} · ${shEsc(p.status||'Current roster')} · Exp ${shEsc(p.experience||'—')}</small></div></div><div class="ps-lines">${stats.map(statLine).join('')||'<span class="ps-no-stats">No individual box-score statistic recorded in the completed preseason game</span>'}</div></article>`}
function filters(){const units=['All','Offense','Defense','Special Teams'];return `<div class="ps-controls"><div>${units.map((u,i)=>`<button class="ps-filter ${i===0?'active':''}" data-unit-filter="${u}">${u}</button>`).join('')}</div><input id="ps-search" type="search" placeholder="Search player or position…" aria-label="Search preseason roster stats"></div>`}
function applyFilters(root){const q=(root.querySelector('#ps-search')?.value||'').toLowerCase(),active=root.querySelector('.ps-filter.active')?.dataset.unitFilter||'All';root.querySelectorAll('.ps-player').forEach(row=>{const okUnit=active==='All'||row.dataset.unit===active,okQ=!q||row.textContent.toLowerCase().includes(q);row.hidden=!(okUnit&&okQ)});}
function teamGrid(stats){const labels={firstDowns:'First downs',thirdDown:'Third down',totalYards:'Total yards',rushingYards:'Rush yards',netPassingYards:'Net pass yards',penalties:'Penalties',fumbles:'Fumbles',touchdowns:'TDs',fieldGoals:'Field goals',timeOfPossession:'Time of possession'};return `<div class="ps-team-grid">${Object.entries(stats||{}).map(([k,v])=>`<span><small>${shEsc(labels[k]||k)}</small><b>${shEsc(v)}</b></span>`).join('')}</div>`}
function sourceLinks(sources){return (sources||[]).map(s=>`<a href="${shEsc(s.url)}" target="_blank" rel="noopener noreferrer">${shEsc(s.label)} ↗</a>`).join('')}
async function renderStats(){if(shRoute()!=='stats')return;const app=document.querySelector('#app');if(!app||app.dataset.preseasonHub==='loading'||app.querySelector('.preseason-stats-hub'))return;app.dataset.preseasonHub='loading';try{const r=await fetch('/api/preseason-stats',{headers:{Accept:'application/json'}}),d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||'Stats unavailable');const head=app.querySelector('.page-head');app.innerHTML='';if(head)app.append(head);const hub=document.createElement('section');hub.className='preseason-stats-hub';const games=(d.completedGames||[]).map(g=>`<span>${shEsc(g.name)} · ${shEsc(g.status)}</span>`).join('');hub.innerHTML=`<div class="ps-summary"><div><small>2026 preseason stat book</small><h2>Full roster + every recorded preseason box-score stat</h2><p>${shEsc(d.rosterSource||'Roster source')} · ${shEsc(d.statsSource||'Stats source')}</p></div><div class="ps-counts"><span><b>${d.rosterCount||0}</b> roster players</span><span><b>${(d.completedGames||[]).length}</b> completed preseason games</span></div></div>${games?`<div class="ps-games">${games}</div>`:''}${teamGrid(d.teamStats)}${(d.diagnostics||[]).length?`<details class="ps-diagnostics"><summary>Feed diagnostics</summary><p>${(d.diagnostics||[]).map(shEsc).join(' · ')}</p></details>`:''}<div class="ps-sources">${sourceLinks(d.sources)}</div>${filters()}<div class="ps-roster">${(d.players||[]).map(playerRow).join('')}</div>${(d.otherParticipants||[]).length?`<details class="ps-former"><summary>Preseason participants not matched to the current roster (${d.otherParticipants.length})</summary><div>${d.otherParticipants.map(playerRow).join('')}</div></details>`:''}<div class="ps-source-note">Stats shown are preseason only. The roster is the full audited current snapshot, so players who did not record an individual box-score statistic still appear. “No individual box-score statistic” does not mean the player was inactive. Roster status and game participation are separate.</div>`;app.append(hub);hub.querySelectorAll('.ps-filter').forEach(b=>b.addEventListener('click',()=>{hub.querySelectorAll('.ps-filter').forEach(x=>x.classList.toggle('active',x===b));applyFilters(hub)}));hub.querySelector('#ps-search')?.addEventListener('input',()=>applyFilters(hub));}catch(e){app.insertAdjacentHTML('beforeend',`<div class="ps-error">Preseason stat feed could not load: ${shEsc(e.message)}. The page will retry on refresh.</div>`)}finally{delete app.dataset.preseasonHub}}
const shRoot=document.querySelector('#app');if(shRoot)new MutationObserver(()=>queueMicrotask(renderStats)).observe(shRoot,{childList:true,subtree:true});addEventListener('hashchange',()=>queueMicrotask(renderStats));queueMicrotask(renderStats);
