const trQs=(s,r=document)=>r.querySelector(s),trQsa=(s,r=document)=>[...r.querySelectorAll(s)];
const trRoute=()=>location.hash.replace(/^#/,'').split('?')[0]||'home';
let trData=null,trPromise=null;
const trEsc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const prettyDate=v=>{if(!v)return 'date unavailable';const d=new Date(`${String(v).slice(0,10)}T12:00:00Z`);return Number.isNaN(d.getTime())?String(v):new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',year:'numeric'}).format(d)};
async function loadTeamRoom(){if(trData)return trData;if(!trPromise)trPromise=fetch('/api/data',{headers:{Accept:'application/json'}}).then(r=>r.json()).then(d=>{if(!d?.ok)throw new Error('team data unavailable');trData=d;return d}).finally(()=>{trPromise=null});return trPromise;}
function rankLabel(rows,row){const tied=rows.filter(x=>x.rank===row.rank).length>1;return tied?`T${row.rank}`:String(row.rank);}
function depthPanel(ctx){
  const depth=ctx?.depthChart;if(!depth?.rows?.length)return '<div class="team-room-empty">Official depth-chart snapshot is not available yet.</div>';
  const units=['Offense','Defense','Special Teams'];
  const columns=units.map(unit=>{const unitRows=depth.rows.filter(r=>r.unit===unit),slots=[...new Set(unitRows.map(r=>r.slot))];return `<section class="depth-unit"><header><span>${trEsc(unit)}</span><small>${slots.length} position groups</small></header><div class="depth-position-list">${slots.map(slot=>{const rows=unitRows.filter(r=>r.slot===slot),pos=rows[0]?.position||'—';return `<article class="depth-position"><div class="depth-position-head"><strong>${trEsc(pos)}</strong><small>${rows.length} listed</small></div><ol>${rows.map(row=>`<li><span class="depth-rank">${rankLabel(rows,row)}</span><a href="#player?id=${encodeURIComponent(row.playerId)}"><b>#${trEsc(row.number||'—')}</b><span>${trEsc(row.name)}</span></a></li>`).join('')}</ol></article>`;}).join('')}</div></section>`;}).join('');
  return `<div class="depth-audit-banner"><div><small>Official team snapshot</small><strong>UNOFFICIAL depth chart · ${prettyDate(depth.sourceDate||depth.capturedAt)}</strong><p>Ties are preserved exactly instead of forcing players into a made-up 1/2/3 order.</p></div><a href="${trEsc(depth.sourceUrl)}" target="_blank" rel="noopener noreferrer">Titans source ↗</a></div><div class="depth-columns">${columns}</div>`;
}
function staffPanel(ctx){const leadership=ctx?.leadership||[],coaches=ctx?.coaching||[],units=['Team','Offense','Defense','Special Teams'];return `<div class="staff-audit-banner"><small>Verified ${trEsc(ctx?.auditedOn||'current')}</small><strong>Football leadership & coaching staff</strong><p>Current roles are sourced from TennesseeTitans.com. Historical or secondary sources do not override the official staff page.</p></div><div class="leadership-grid">${leadership.map(x=>`<article><small>${trEsc(x.role)}</small><strong>${trEsc(x.name)}</strong></article>`).join('')}</div><div class="staff-unit-grid">${units.map(unit=>`<section><h3>${unit}</h3>${coaches.filter(c=>c.unit===unit).map(c=>`<div class="staff-row"><span>${trEsc(c.role)}</span><strong>${trEsc(c.name)}</strong></div>`).join('')}</section>`).join('')}</div>`;}
function setRosterView(view){const app=trQs('#app');if(!app)return;app.dataset.teamRoomView=view;trQsa('[data-team-room-view]',app).forEach(b=>{const on=b.dataset.teamRoomView===view;b.classList.toggle('active',on);b.setAttribute('aria-selected',String(on));});trQsa('.team-room-panel',app).forEach(p=>p.hidden=p.dataset.panel!==view);}
async function enhanceRoster(){
  const app=trQs('#app'),head=trQs('.page-head',app),grid=trQs('#rg',app);if(!app||!head||!grid||trQs('.team-room-switcher',app))return;
  const switcher=document.createElement('div');switcher.className='team-room-switcher';switcher.setAttribute('role','tablist');switcher.setAttribute('aria-label','Team view');switcher.innerHTML='<button type="button" role="tab" data-team-room-view="roster" class="active" aria-selected="true">Roster</button><button type="button" role="tab" data-team-room-view="depth" aria-selected="false">Depth Chart</button><button type="button" role="tab" data-team-room-view="staff" aria-selected="false">Staff</button>';head.insertAdjacentElement('afterend',switcher);
  const depth=document.createElement('section');depth.className='team-room-panel';depth.dataset.panel='depth';depth.hidden=true;depth.innerHTML='<div class="team-room-loading">Loading official depth-chart snapshot…</div>';
  const staff=document.createElement('section');staff.className='team-room-panel';staff.dataset.panel='staff';staff.hidden=true;staff.innerHTML='<div class="team-room-loading">Loading verified staff…</div>';switcher.insertAdjacentElement('afterend',staff);switcher.insertAdjacentElement('afterend',depth);
  trQsa('button',switcher).forEach(btn=>btn.addEventListener('click',()=>setRosterView(btn.dataset.teamRoomView)));
  try{const data=await loadTeamRoom();depth.innerHTML=depthPanel(data.teamContext);staff.innerHTML=staffPanel(data.teamContext);}catch{depth.innerHTML=staff.innerHTML='<div class="team-room-empty">Verified team-room data is temporarily unavailable.</div>';}
}
async function enhanceStats(){const app=trQs('#app'),head=trQs('.page-head',app);if(!app||!head||trQs('.verified-baseline',app))return;try{const data=await loadTeamRoom(),base=data.teamContext?.baselineStats;if(!base)return;const section=document.createElement('section');section.className='verified-baseline';section.innerHTML=`<div class="baseline-head"><div><small>Season separation</small><h2>${trEsc(base.label)}</h2><p>2026 regular-season statistics have not started. These cards are a clearly labeled prior-season reference, not current-season totals.</p></div><span>2025 REG</span></div><div class="baseline-grid">${base.players.map(p=>`<article><div><small>${trEsc(p.position)}</small><strong>${trEsc(p.name)}</strong></div><ul>${p.lines.map(x=>`<li>${trEsc(x)}</li>`).join('')}</ul><a href="${trEsc(p.sourceUrl)}" target="_blank" rel="noopener noreferrer">NFL stats ↗</a></article>`).join('')}</div>`;head.insertAdjacentElement('afterend',section);}catch{}}
async function enhanceInjuryState(){const app=trQs('#app'),head=trQs('.page-head',app);if(!app||!head||trQs('.official-injury-state',app))return;try{const data=await loadTeamRoom(),inj=data.teamContext?.injuryReport;if(!inj)return;const el=document.createElement('aside');el.className='official-injury-state';el.innerHTML=`<div><small>2026 injury-report status</small><strong>${trEsc(inj.label)}</strong><p>${trEsc(inj.detail)}</p></div><a href="${trEsc(inj.sourceUrl)}" target="_blank" rel="noopener noreferrer">Official report ↗</a>`;head.insertAdjacentElement('afterend',el);}catch{}}
async function enhanceSources(){const app=trQs('#app'),head=trQs('.page-head',app);if(!app||!head||trQs('.source-arbitration',app))return;try{const data=await loadTeamRoom(),policy=data.teamContext?.sourcePolicy,conflicts=data.teamContext?.knownConflicts||[];if(!policy)return;const el=document.createElement('section');el.className='source-arbitration';el.innerHTML=`<div class="source-priority"><small>Fact arbitration</small><h2>Not all sources are equal.</h2><p>${trEsc(policy.rule)}</p><div><span>1 · Titans official</span><span>2 · NFL / Hall of Fame</span><span>3 · PFR / nflverse / SportsLogos</span><span>4 · Wikipedia / community</span></div></div><details><summary>Known source conflicts caught by the audit</summary>${conflicts.map(c=>`<article><strong>${trEsc(c.topic)}</strong><p>${trEsc(c.resolution)}</p><small>Conflict: ${trEsc(c.secondaryValue)}</small></article>`).join('')}</details>`;head.insertAdjacentElement('afterend',el);}catch{}}
function applyTeamRoom(){const route=trRoute();if(route==='roster')enhanceRoster();if(route==='stats')enhanceStats();if(route==='live'||route==='roster')enhanceInjuryState();if(route==='sources')enhanceSources();}
const trApp=trQs('#app');if(trApp)new MutationObserver(()=>queueMicrotask(applyTeamRoom)).observe(trApp,{childList:true,subtree:true});addEventListener('hashchange',()=>queueMicrotask(applyTeamRoom));queueMicrotask(applyTeamRoom);
