const trQs=(s,r=document)=>r.querySelector(s),trQsa=(s,r=document)=>[...r.querySelectorAll(s)];
const trRoute=()=>location.hash.replace(/^#/,'').split('?')[0]||'home';
const TR_VIEWS=new Set(['roster','depth','staff','cutdown']);
let trData=null,trPromise=null,trPreferredRosterView='roster';
const trEsc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const trSafeUrl=v=>{try{const u=new URL(String(v||''),location.origin);return ['http:','https:'].includes(u.protocol)?u.href:''}catch{return''}};
const prettyDate=v=>{if(!v)return 'date unavailable';const d=new Date(`${String(v).slice(0,10)}T12:00:00Z`);return Number.isNaN(d.getTime())?'date unavailable':new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',year:'numeric'}).format(d)};
const sourceLink=(url,label)=>{const safe=trSafeUrl(url);return safe?`<a href="${trEsc(safe)}" target="_blank" rel="noopener noreferrer">${trEsc(label)} ↗</a>`:''};
const requestedRosterView=()=>{const value=new URLSearchParams(location.hash.split('?')[1]||'').get('view');return TR_VIEWS.has(value)?value:null};
const trBegin=(app,key)=>{if(!app||app.dataset[key]==='1')return false;app.dataset[key]='1';return true};
const trEnd=(app,key)=>{if(app)delete app.dataset[key]};
async function loadTeamRoom(){if(trData)return trData;if(!trPromise)trPromise=fetch('/api/data',{headers:{Accept:'application/json'},cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok||!d?.ok)throw new Error('team data unavailable');trData=d;return d}).finally(()=>{trPromise=null});return trPromise;}
function rankLabel(rows,row){const tied=rows.filter(x=>x.rank===row.rank).length>1;return tied?`T${row.rank}`:String(row.rank);}
function depthPanel(ctx){const depth=ctx?.depthChart;if(!depth?.rows?.length)return '<div class="team-room-empty">Official depth-chart snapshot is not available yet.</div>';const units=['Offense','Defense','Special Teams'];const columns=units.map(unit=>{const unitRows=depth.rows.filter(r=>r.unit===unit),slots=[...new Set(unitRows.map(r=>r.slot))];return `<section class="depth-unit"><header><span>${trEsc(unit)}</span><small>${slots.length} position groups</small></header><div class="depth-position-list">${slots.map(slot=>{const rows=unitRows.filter(r=>r.slot===slot),pos=rows[0]?.position||'—';return `<article class="depth-position"><div class="depth-position-head"><strong>${trEsc(pos)}</strong><small>${rows.length} listed</small></div><ol>${rows.map(row=>`<li><span class="depth-rank">${rankLabel(rows,row)}</span><a href="#player?id=${encodeURIComponent(row.playerId)}"><b>#${trEsc(row.number||'—')}</b><span>${trEsc(row.name)}</span></a></li>`).join('')}</ol></article>`;}).join('')}</div></section>`;}).join('');return `<div class="depth-audit-banner"><div><small>Official team snapshot</small><strong>UNOFFICIAL depth chart · ${prettyDate(depth.sourceDate||depth.capturedAt)}</strong><p>Ties are preserved exactly instead of forcing players into a made-up 1/2/3 order. This is a dated snapshot, not a permanent starter list.</p></div>${sourceLink(depth.sourceUrl,'Titans source')}</div><div class="depth-columns">${columns}</div>`;}
function staffPanel(ctx){const leadership=ctx?.leadership||[],coaches=ctx?.coaching||[],units=['Team','Offense','Defense','Special Teams'],official=ctx?.coachingSourceUrl||'https://www.tennesseetitans.com/team/coaches-roster/';return `<div class="staff-audit-banner"><div><small>Official staff · updated ${trEsc(ctx?.coachingUpdatedOn||ctx?.auditedOn||'current')}</small><strong>Football leadership & complete coaching staff</strong><p>Current titles are sourced from TennesseeTitans.com. The official current staff page controls over secondary bios, old articles, or search snippets.</p></div>${sourceLink(official,'Official staff')}</div><div class="leadership-grid">${leadership.map(x=>`<article><small>${trEsc(x.role)}</small><strong>${trEsc(x.name)}</strong></article>`).join('')}</div><div class="staff-count-row"><span>${coaches.length} verified coaching roles</span>${sourceLink(ctx?.leadershipSourceUrl||'https://www.tennesseetitans.com/team/front-office-roster/','Front office source')}</div><div class="staff-unit-grid">${units.map(unit=>`<section><h3>${unit} <small>${coaches.filter(c=>c.unit===unit).length}</small></h3>${coaches.filter(c=>c.unit===unit).map(c=>`<div class="staff-row"><span>${trEsc(c.role)}</span><strong>${trEsc(c.name)}</strong></div>`).join('')}</section>`).join('')}</div>`;}
function syncRosterBaseVisibility(app,view){const hide=view!=='roster';trQsa('.roster-summary-strip,.filterbar,.roster-status-filters,#rg',app).forEach(el=>{el.hidden=hide;});}
function setRosterView(view,{focus=false,persist=true}={}){const app=trQs('#app');if(!app)return;const next=TR_VIEWS.has(view)?view:'roster';if(persist)trPreferredRosterView=next;app.dataset.teamRoomView=next;trQsa('[data-team-room-view]',app).forEach(b=>{const on=b.dataset.teamRoomView===next;b.classList.toggle('active',on);b.setAttribute('aria-pressed',String(on));if(on&&focus)b.focus();});trQsa('.team-room-panel',app).forEach(p=>p.hidden=p.dataset.panel!==next);syncRosterBaseVisibility(app,next);}
function wireTeamRoomSwitcher(switcher){const buttons=trQsa('[data-team-room-view]',switcher);buttons.forEach((btn,index)=>btn.addEventListener('keydown',event=>{let next=null;if(event.key==='ArrowRight')next=(index+1)%buttons.length;if(event.key==='ArrowLeft')next=(index-1+buttons.length)%buttons.length;if(event.key==='Home')next=0;if(event.key==='End')next=buttons.length-1;if(next==null)return;event.preventDefault();const target=buttons[next];setRosterView(target.dataset.teamRoomView,{focus:true});}));}
async function fillTeamRoomPanels(depth,staff){depth.innerHTML='<div class="team-room-loading" role="status">Loading official depth-chart snapshot…</div>';staff.innerHTML='<div class="team-room-loading" role="status">Loading verified staff…</div>';try{const data=await loadTeamRoom();if(!depth.isConnected||!staff.isConnected)return;depth.innerHTML=depthPanel(data.teamContext);staff.innerHTML=staffPanel(data.teamContext);}catch{if(!depth.isConnected||!staff.isConnected)return;const retry='<div class="team-room-empty"><div>Verified team-room data is temporarily unavailable.</div><button type="button" class="button" data-team-room-retry>Try again</button></div>';depth.innerHTML=staff.innerHTML=retry;trQsa('[data-team-room-retry]',depth).concat(trQsa('[data-team-room-retry]',staff)).forEach(btn=>btn.addEventListener('click',()=>{trData=null;trPromise=null;fillTeamRoomPanels(depth,staff)},{once:true}));}}
function enhanceRoster(){const app=trQs('#app'),head=trQs('.page-head',app),grid=trQs('#rg',app);if(!app||!head||!grid||trQs('.team-room-switcher',app))return;const switcher=document.createElement('div');switcher.className='team-room-switcher';switcher.setAttribute('role','group');switcher.setAttribute('aria-label','Team view');switcher.innerHTML='<button type="button" data-team-room-view="roster" class="active" aria-pressed="true">Roster</button><button type="button" data-team-room-view="depth" aria-pressed="false">Depth Chart</button><button type="button" data-team-room-view="staff" aria-pressed="false">Staff</button><button type="button" data-team-room-view="cutdown" aria-pressed="false">Cutdown</button>';head.insertAdjacentElement('afterend',switcher);const depth=document.createElement('section');depth.className='team-room-panel';depth.dataset.panel='depth';depth.hidden=true;const staff=document.createElement('section');staff.className='team-room-panel';staff.dataset.panel='staff';staff.hidden=true;const cutdown=document.createElement('section');cutdown.className='team-room-panel';cutdown.dataset.panel='cutdown';cutdown.hidden=true;switcher.insertAdjacentElement('afterend',cutdown);switcher.insertAdjacentElement('afterend',staff);switcher.insertAdjacentElement('afterend',depth);trQsa('button',switcher).forEach(btn=>btn.addEventListener('click',()=>setRosterView(btn.dataset.teamRoomView)));wireTeamRoomSwitcher(switcher);setRosterView(requestedRosterView()||trPreferredRosterView,{persist:false});fillTeamRoomPanels(depth,staff);}
async function enhanceStats(){const app=trQs('#app'),head=trQs('.page-head',app);if(!app||!head||trQs('.verified-baseline',app)||!trBegin(app,'trStatsPending'))return;try{const data=await loadTeamRoom(),base=data.teamContext?.baselineStats;if(!base||!app.isConnected||!head.isConnected||trRoute()!=='stats'||trQs('.verified-baseline',app))return;const section=document.createElement('section');section.className='verified-baseline';section.innerHTML=`<div class="baseline-head"><div><small>Season separation</small><h2>${trEsc(base.label)}</h2><p>2026 regular-season statistics have not started. These cards are a clearly labeled prior-season reference, not current-season totals.</p></div><span>2025 REG</span></div><div class="baseline-grid">${base.players.map(p=>`<article><div><small>${trEsc(p.position)}</small><strong>${trEsc(p.name)}</strong></div><ul>${p.lines.map(x=>`<li>${trEsc(x)}</li>`).join('')}</ul>${sourceLink(p.sourceUrl||base.sourceUrl,'Titans stats')}</article>`).join('')}</div><div class="baseline-source-note">Primary source: ${sourceLink(base.sourceUrl,base.sourceLabel||'Tennessee Titans official team statistics')}</div>`;head.insertAdjacentElement('afterend',section);}catch{}finally{trEnd(app,'trStatsPending');}}
async function enhanceInjuryState(){const app=trQs('#app'),head=trQs('.page-head',app);if(!app||!head||trQs('.official-injury-state',app)||!trBegin(app,'trInjuryPending'))return;try{const data=await loadTeamRoom(),inj=data.teamContext?.injuryReport;if(!inj||!app.isConnected||!head.isConnected||!['live','roster'].includes(trRoute())||trQs('.official-injury-state',app))return;const el=document.createElement('aside');el.className='official-injury-state';el.innerHTML=`<div><small>2026 injury-report status</small><strong>${trEsc(inj.label)}</strong><p>${trEsc(inj.detail)}</p></div>${sourceLink(inj.sourceUrl,'Official report')}`;head.insertAdjacentElement('afterend',el);}catch{}finally{trEnd(app,'trInjuryPending');}}
function domainCard(d){return `<article class="source-domain-card"><small>${trEsc(d.label)}</small><div class="source-level primary"><b>Primary</b><span>${trEsc(d.primary)}</span></div><div class="source-level"><b>Cross-check</b><span>${trEsc(d.crossCheck)}</span></div><div class="source-level secondary"><b>Secondary</b><span>${trEsc(d.secondary)}</span></div><p>${trEsc(d.note)}</p></article>`;}
async function enhanceSources(){const app=trQs('#app'),head=trQs('.page-head',app);if(!app||!head||trQs('.source-arbitration',app)||!trBegin(app,'trSourcesPending'))return;try{const data=await loadTeamRoom(),policy=data.teamContext?.sourcePolicy,conflicts=data.teamContext?.knownConflicts||[];if(!policy||!app.isConnected||!head.isConnected||trRoute()!=='sources'||trQs('.source-arbitration',app))return;const domains=policy.domains||[],el=document.createElement('section');el.className='source-arbitration';el.innerHTML=`<div class="source-priority"><small>How facts are checked</small><h2>Best source depends on the fact.</h2><p>${trEsc(policy.rule)}</p>${domains.length?`<div class="source-domain-grid">${domains.map(domainCard).join('')}</div>`:''}</div><details><summary>Source conflicts already caught · ${conflicts.length}</summary>${conflicts.map(c=>`<article><strong>${trEsc(c.topic)}</strong><p>${trEsc(c.resolution)}</p><small>Conflicting value: ${trEsc(c.secondaryValue)}</small></article>`).join('')}</details>`;head.insertAdjacentElement('afterend',el);}catch{}finally{trEnd(app,'trSourcesPending');}}
function applyTeamRoom(){const route=trRoute();if(route==='roster'){enhanceRoster();const app=trQs('#app');if(app&&trQs('.team-room-switcher',app))setRosterView(app.dataset.teamRoomView||requestedRosterView()||trPreferredRosterView,{persist:false});}if(route==='stats')enhanceStats();if(route==='live'||route==='roster')enhanceInjuryState();if(route==='sources')enhanceSources();}
const trApp=trQs('#app');if(trApp)new MutationObserver(()=>queueMicrotask(applyTeamRoom)).observe(trApp,{childList:true});addEventListener('hashchange',()=>queueMicrotask(applyTeamRoom));queueMicrotask(applyTeamRoom);
