import test from 'node:test';
import assert from 'node:assert/strict';
import {aggregatePlayerStats,aggregateTeamStats,buildLeaders,positionCounts} from '../src/preseason-model.mjs';
const rows=[
  {category:'Passing',fields:[{label:'CMP/ATT',value:'5/12'},{label:'YDS',value:'57'},{label:'SACK',value:'0/0'},{label:'TD',value:'0'},{label:'INT',value:'0'}]},
  {category:'Passing',fields:[{label:'CMP/ATT',value:'10/15'},{label:'YDS',value:'120'},{label:'SACK',value:'1/8'},{label:'TD',value:'1'},{label:'INT',value:'0'}]},
  {category:'Rushing',fields:[{label:'ATT',value:'4'},{label:'YDS',value:'22'},{label:'AVG',value:'5.5'},{label:'LG',value:'12'},{label:'TD',value:'1'}]},
  {category:'Rushing',fields:[{label:'ATT',value:'6'},{label:'YDS',value:'30'},{label:'AVG',value:'5.0'},{label:'LG',value:'9'},{label:'TD',value:'0'}]}
];
test('player preseason totals aggregate counting stats and recompute rates',()=>{const totals=aggregatePlayerStats(rows),passing=totals.find(x=>x.category==='Passing'),rushing=totals.find(x=>x.category==='Rushing');assert.equal(passing.fields.find(x=>x.label==='CMP/ATT').value,'15/27');assert.equal(passing.fields.find(x=>x.label==='YDS').value,'177');assert.equal(passing.fields.find(x=>x.label==='TD').value,'1');assert.equal(rushing.fields.find(x=>x.label==='ATT').value,'10');assert.equal(rushing.fields.find(x=>x.label==='YDS').value,'52');assert.equal(rushing.fields.find(x=>x.label==='AVG').value,'5.2');assert.equal(rushing.fields.find(x=>x.label==='LG').value,'12')});
test('team totals combine multi-game pairs and time of possession',()=>{const total=aggregateTeamStats([{firstDowns:'18',thirdDown:'4/12 (33.3%)',totalYards:'279',rushingYards:'167',netPassingYards:'112',penalties:'9-67',fumbles:'3-0',touchdowns:'1',fieldGoals:'4/4',timeOfPossession:'27:12'},{firstDowns:'20',thirdDown:'5/11',totalYards:'300',rushingYards:'120',netPassingYards:'180',penalties:'4-30',fumbles:'1-1',touchdowns:'2',fieldGoals:'1/2',timeOfPossession:'31:00'}]);assert.equal(total.firstDowns,'38');assert.equal(total.thirdDown,'9/23 (39.1%)');assert.equal(total.totalYards,'579');assert.equal(total.penalties,'13-97');assert.equal(total.fieldGoals,'5/6');assert.equal(total.timeOfPossession,'58:12')});
test('position counts and leaders cover the full roster model',()=>{const players=[{name:'QB One',number:'1',position:'QB',seasonStats:aggregatePlayerStats(rows)},{name:'QB Two',number:'8',position:'QB',seasonStats:[]},{name:'Runner',number:'20',position:'RB',seasonStats:aggregatePlayerStats([{category:'Rushing',fields:[{label:'ATT',value:'8'},{label:'YDS',value:'60'},{label:'TD',value:'0'}]}])}];assert.deepEqual(positionCounts(players).map(x=>[x.position,x.count]),[['QB',2],['RB',1]]);assert.equal(buildLeaders(players).find(x=>x.title==='Rushing yards').name,'Runner')});
test('ESPN-style stat labels normalize into season totals',()=>{const totals=aggregatePlayerStats([{category:'Passing',fields:[{label:'C/ATT',value:'7/10'},{label:'YDS',value:'88'},{label:'SACKS',value:'1/7'},{label:'TD',value:'1'},{label:'INT',value:'0'}]},{category:'Rushing',fields:[{label:'CAR',value:'3'},{label:'YDS',value:'21'},{label:'LONG',value:'12'},{label:'TD',value:'0'}]},{category:'Defense',fields:[{label:'SOLO',value:'4'},{label:'AST',value:'2'},{label:'TOT',value:'6'},{label:'SACKS',value:'1'},{label:'QB HTS',value:'2'}]}]);assert.equal(totals.find(x=>x.category==='Passing').fields.find(x=>x.label==='CMP/ATT').value,'7/10');assert.equal(totals.find(x=>x.category==='Rushing').fields.find(x=>x.label==='ATT').value,'3');assert.equal(totals.find(x=>x.category==='Defense').fields.find(x=>x.label==='COMB').value,'6');assert.equal(totals.find(x=>x.category==='Defense').fields.find(x=>x.label==='QH').value,'2')});
