import test from 'node:test';
import assert from 'node:assert/strict';
import { auditedTeamContext } from '../src/team-context.mjs';

test('source policy prioritizes official current sources and varies by domain',()=>{assert.deepEqual(auditedTeamContext.sourcePolicy.currentTeamData,['Tennessee Titans','NFL.com']);assert.match(auditedTeamContext.sourcePolicy.rule,/domain-specific/i);assert.match(auditedTeamContext.sourcePolicy.rule,/newer dated transaction/i);const stats=auditedTeamContext.sourcePolicy.domains.find(x=>x.key==='statistics'),visuals=auditedTeamContext.sourcePolicy.domains.find(x=>x.key==='visuals');assert.match(stats.primary,/Titans structured team stats/i);assert.match(visuals.primary,/Titans brand/i);});
test('regular-season injury-report gap is not presented as zero injuries',()=>{assert.equal(auditedTeamContext.injuryReport.status,'not-yet-published-2026');assert.match(auditedTeamContext.injuryReport.detail,/Reserve\/Injured roster status is tracked separately/);assert.match(auditedTeamContext.injuryReport.detail,/regular season/i);});
test('verified baseline is explicitly prior season and uses official Titans stats as primary',()=>{assert.equal(auditedTeamContext.baselineStats.season,2025);assert.match(auditedTeamContext.baselineStats.label,/not 2026 regular-season stats/i);assert.match(auditedTeamContext.baselineStats.sourceUrl,/tennesseetitans\.com\/team\/stats\/2025\/REG/);assert.equal(auditedTeamContext.baselineStats.players.find(p=>p.name==='Cam Ward').lines.includes('3,169 pass yds'),true);assert.equal(auditedTeamContext.baselineStats.players.find(p=>p.name==='Jeffery Simmons').lines.includes('67 total tackles'),true);});
test('current 2026 leadership titles and complete coaching staff are audited',()=>{assert.equal(auditedTeamContext.leadership.find(x=>x.name==='Amy Adams Strunk').role,'Controlling Owner/Co-Chairman, Board of Directors');assert.equal(auditedTeamContext.leadership.find(x=>x.role==='General Manager').name,'Mike Borgonzi');assert.equal(auditedTeamContext.coaching.find(x=>x.role==='Head Coach').name,'Robert Saleh');assert.equal(auditedTeamContext.coaching.find(x=>x.role==='Offensive Coordinator').name,'Brian Daboll');assert.equal(auditedTeamContext.coaching.find(x=>x.role==='Defensive Coordinator').name,'Gus Bradley');assert.equal(auditedTeamContext.coaching.find(x=>x.role==='Chief of Staff').name,'Rob Dadona');assert.equal(auditedTeamContext.coaching.length,23);});
test('current depth chart stays explicitly unofficial and dated',()=>{assert.equal(auditedTeamContext.depthChartPolicy.status,'dated-unofficial-snapshot');assert.equal(auditedTeamContext.depthChartPolicy.sourceDate,'2026-08-25');assert.match(auditedTeamContext.depthChartPolicy.label,/UNOFFICIAL/i);assert.match(auditedTeamContext.depthChartPolicy.detail,/predates/i);});
test('known secondary schedule conflict is documented',()=>{const conflict=auditedTeamContext.knownConflicts.find(x=>x.topic==='2026 preseason opener date');assert.ok(conflict);assert.match(conflict.resolution,/Aug\. 13/);});
test('known Jeffery Simmons stat-source conflict is documented',()=>{const conflict=auditedTeamContext.knownConflicts.find(x=>x.topic==='Jeffery Simmons 2025 total tackles');assert.ok(conflict);assert.match(conflict.officialValue,/67/);assert.match(conflict.secondaryValue,/65/);});
test('known Cedric Gray official-source conflict is documented',()=>{const conflict=auditedTeamContext.knownConflicts.find(x=>x.topic==='Cedric Gray 2025 total tackles');assert.ok(conflict);assert.match(conflict.officialValue,/164/);assert.match(conflict.secondaryValue,/160/);});
test('official transaction typo cannot overwrite Mario Goodrich identity',()=>{const conflict=auditedTeamContext.knownConflicts.find(x=>/Mario Goodrich III identity/.test(x.topic));assert.ok(conflict);assert.match(conflict.officialValue,/Goodrich III/);assert.match(conflict.secondaryValue,/Goodson III/);});
test('visual policy only treats the Shield as current primary',()=>{assert.equal(auditedTeamContext.visualAudit.currentPrimary,'The Shield');assert.match(auditedTeamContext.visualAudit.rule,/exact variant\/year has been verified/i);assert.match(auditedTeamContext.visualAudit.rule,/reference art/i);});
