import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { team, games, roster, feed, sources } from '../src/data.mjs';
import { auditedPracticeSquad20260902, ROSTER_AUDIT_DATE, ROSTER_SOURCE_CONFLICT } from '../src/roster-audit-20260831.mjs';
import { auditedTeamContext } from '../src/team-context.mjs';
import { legacyTimeline, visualArchive, knownVisualsNotPictured, visualSources } from '../src/visual-audit.mjs';

const errors=[];
const check=(label,fn)=>{try{fn();console.log(`✓ ${label}`)}catch(error){errors.push(`${label}: ${error.message}`);console.error(`✗ ${label}`)}};
check('current team identity metadata',()=>{assert.equal(team.name,'Tennessee Titans');assert.equal(team.coach,'Robert Saleh');assert.equal(team.generalManager,'Mike Borgonzi');assert.equal(team.owner,'Amy Adams Strunk');assert.equal(team.president,'Burke Nihill');assert.equal(team.presidentTitle,'President and Chief Executive Officer');assert.equal(team.offensiveCoordinator,'Brian Daboll');assert.equal(team.defensiveCoordinator,'Gus Bradley');assert.equal(team.specialTeamsCoordinator,'John Fassel');assert.deepEqual(team.colors,['Titans blue','red','white','navy blue']);assert.equal(team.primaryLogo,'The Shield');assert.equal(team.phase,'Regular Season');});
check('franchise milestone dates preserve 1959 vs 1960 distinction',()=>{assert.equal(team.franchiseGranted,'1959-08-14');assert.equal(team.firstSeason,1960);assert.equal(team.firstSeasonInTennessee,1997);assert.equal(team.firstSeasonAsTitans,1999);});
check('2026 schedule contains Week 9 bye',()=>{assert.ok(games.find(g=>g.week===9&&g.status==='bye'),'Week 9 bye is missing');});
check('Week 18 stays genuinely TBD at current Reliant Stadium name',()=>{const week18=games.find(g=>g.week===18&&g.opponentAbbr==='HOU');assert.ok(week18,'Week 18 at Houston is missing');assert.equal(week18.date,null);assert.equal(week18.dateTbd,true);assert.equal(week18.network,'TBD');assert.equal(week18.venue,'Reliant Stadium');});
check('preseason is complete at 2-1 and Jets are the next scheduled opponent',()=>{const preseason=games.filter(g=>String(g.week).startsWith('P'));assert.equal(preseason.length,3);assert.equal(preseason.filter(g=>g.status==='final').length,3);assert.equal(preseason.filter(g=>g.score>g.opponentScore).length,2);assert.equal(preseason.filter(g=>g.score<g.opponentScore).length,1);const bears=games.find(g=>g.opponentAbbr==='CHI');assert.equal(bears.score,15);assert.equal(bears.opponentScore,24);assert.match(bears.network,/NFL Network/);assert.match(bears.network,/WKRN-TV News 2/);const jets=games.find(g=>g.week===1);assert.equal(jets.opponentAbbr,'NYJ');assert.equal(jets.status,'scheduled');assert.equal(jets.network,'CBS');});
check('fallback roster reflects the Sept. 2 official current-team snapshot',()=>{assert.equal(ROSTER_AUDIT_DATE,'2026-09-02');assert.equal(team.rosterCoverage.fallbackType,'cross-source-audited-snapshot');assert.equal(team.rosterCoverage.fallbackPlayers,roster.length);assert.equal(team.rosterCoverage.asOf,'2026-09-02');assert.equal(team.rosterCoverage.sourceConflict,ROSTER_SOURCE_CONFLICT);assert.equal(roster.length,60);assert.equal(roster.filter(p=>p.status==='Active').length,53);assert.equal(roster.filter(p=>p.status==='Reserve/Injured').length,5);assert.equal(roster.filter(p=>p.status==='Reserve/Injured; Designated for Return').length,2);assert.equal(auditedPracticeSquad20260902.length,17);assert.equal(new Set(roster.map(p=>p.name)).size,60);for(const [name,number] of [['Owen Pappoe','40'],['Nazir Stackhouse','93'],['Terrell Burgess','38'],['James Hudson III','59'],['Melvin Smith Jr.','39'],['Tony Adams','29']])assert.ok(roster.some(p=>p.name===name&&p.status==='Active'&&p.number===number),`${name} missing or has stale jersey data`);for(const name of ['Will Levis','Cordell Volson','Austin Deculus','Andre James','Xavier Restrepo','Jerrick Reed II','Erick Hallett II','Mohamoud Diabate'])assert.equal(roster.some(p=>p.name===name),false,`${name} should not remain in the current 53/reserve fallback`);for(const name of ['Xavier Restrepo','Jerrick Reed II','Erick Hallett II','Mohamoud Diabate'])assert.ok(auditedPracticeSquad20260902.some(p=>p.name===name),`${name} missing from current practice squad`);for(const name of ['Hank Beatty','Derrick Canteen','Mani Powell','Mario Goodrich III'])assert.equal(auditedPracticeSquad20260902.some(p=>p.name===name),false,`${name} should not remain on the current practice squad`);assert.ok(roster.some(p=>p.name==='Dorian Mausi'&&p.status==='Reserve/Injured; Designated for Return'));assert.ok(roster.some(p=>p.name==='Joshua Williams'&&p.status==='Reserve/Injured; Designated for Return'));});
check('cross-source roster conflicts are explicit and freshness-aware',()=>{assert.equal(auditedTeamContext.auditedOn,'2026-09-02');const current=auditedTeamContext.knownConflicts.find(x=>/Sept\. 2 current roster propagation/i.test(x.topic));assert.ok(current,'Sept. 2 roster propagation conflict is missing');assert.match(current.resolution,/latest dated Titans transaction/i);assert.match(auditedTeamContext.sourcePolicy.rule,/newer dated transaction/i);assert.match(ROSTER_SOURCE_CONFLICT,/roster table/i);});
check('fallback player metadata avoids unsupported editorial tags',()=>{for(const player of roster)assert.equal('tag' in player,false,`${player.name} has an unsupported editorial tag`);});
check('Peter Skoronski fallback position matches official roster',()=>{assert.equal(roster.find(p=>p.name==='Peter Skoronski')?.position,'G');});
check('fallback feed carries Sept. 2 roster truth and the Bears final',()=>{const sept2=feed.find(x=>/add four to practice squad/i.test(x.title));assert.ok(sept2);assert.match(sept2.url,/titans-add-four-to-practice-squad-waive-three/);assert.match(sept2.summary,/Xavier Restrepo/);const sept1=feed.find(x=>/Sept\. 1 roster transactions/i.test(x.title));assert.ok(sept1);assert.match(sept1.summary,/Andre James/);const update=feed.find(x=>/Updated 53-man roster/i.test(x.title));assert.ok(update);assert.match(update.url,/titans-add-five-players-part-ways-with-five-others/);const cutdown=feed.find(x=>/trim roster to 53/i.test(x.title));assert.ok(cutdown);assert.match(cutdown.url,/titans-trim-roster-to-53-players/);const game=feed.find(x=>/Bears 24, Titans 15/i.test(x.title));assert.ok(game);assert.match(game.url,/titans-end-preseason-with-24-15-loss-to-the-bears/);});
check('fallback feed contains sourceable links instead of placeholder social claims',()=>{assert.ok(feed.length>0);for(const item of feed){assert.match(item.url,/^https:\/\//,`${item.id} does not link to an external source`);assert.notEqual(item.source,'Reporter watchlist');}});
check('fallback source labels distinguish primary authorities from secondary cross-checks',()=>{assert.match(sources.find(s=>s.name==='NFLverse')?.status||'',/importer pending/i);assert.match(sources.find(s=>s.name==='NWS')?.status||'',/persistence pending/i);assert.match(sources.find(s=>s.name==='ESPN')?.purpose||'',/not authoritative roster or injury/i);assert.match(sources.find(s=>s.name==='Pro Football Reference')?.purpose||'',/cannot override official dates, TBD schedule fields/i);assert.match(sources.find(s=>s.name==='SportsLogos.net')?.purpose||'',/official brand\/history pages remain primary/i);});
check('injury, depth chart, and staff semantics remain conservative',()=>{assert.equal(auditedTeamContext.injuryReport.status,'not-yet-published-2026');assert.match(auditedTeamContext.injuryReport.detail,/regular season/i);assert.match(auditedTeamContext.injuryReport.detail,/Reserve\/Injured roster status is tracked separately/);assert.equal(auditedTeamContext.depthChartPolicy.status,'dated-unofficial-snapshot');assert.equal(auditedTeamContext.depthChartPolicy.sourceDate,'2026-08-25');assert.match(auditedTeamContext.depthChartPolicy.label,/UNOFFICIAL/i);assert.equal(auditedTeamContext.coachingUpdatedOn,'2026-09-02');assert.ok(auditedTeamContext.coaching.some(c=>c.name==='Brian Daboll'&&c.role==='Offensive Coordinator'));assert.ok(auditedTeamContext.coaching.some(c=>c.name==='Gus Bradley'&&c.role==='Defensive Coordinator'));assert.ok(auditedTeamContext.coaching.some(c=>c.name==='John Fassel'&&/Assistant Head Coach/.test(c.role)));});
check('visual labels are source-audited and active art avoids legacy aliases',()=>{assert.match(visualSources.wikipedia.url,/wikipedia\.org/);assert.match(visualSources.sportsLogos.url,/sportslogos\.net/);for(const item of visualArchive){assert.doesNotMatch(item.image,/\/assets\/legacy\//,`${item.id} uses an ambiguous legacy alias`);assert.ok(item.alt.length>=35,`${item.id} needs comprehensive alt text`);assert.ok(item.sourceKeys.length>=2,`${item.id} needs at least two source references`);}const uniform2018=legacyTimeline.find(x=>x.id==='2018-uniform-era');assert.match(uniform2018?.copy||'',/fireball-T remained the primary mark through 2025/i);assert.equal(visualArchive.some(item=>/Sword alternate|Vintage roundel/i.test(item.title)),false);const sword=knownVisualsNotPictured.find(item=>item.id==='titans-sword-alternate');assert.match(sword?.copy||'',/real Titans secondary\/alternate mark/i);assert.equal(auditedTeamContext.visualAudit.currentPrimary,'The Shield');assert.match(auditedTeamContext.visualAudit.rule,/reference art/i);});
check('base app no longer requests retired duplicate legacy assets',()=>{const app=readFileSync(new URL('../app.js',import.meta.url),'utf8');assert.doesNotMatch(app,/\/assets\/legacy\//);assert.doesNotMatch(app,/legacy-(?:banner|derrick|fireball|lightblue-wordmark|logo-evolution|sword|vintage-roundel|wordmark-fireball)\.webp/);});
check('responsive system has deliberate phone, tablet and desktop modes',()=>{const css=readFileSync(new URL('../viewport-polish-v101.css',import.meta.url),'utf8');assert.match(css,/@media \(max-width:759px\)/);assert.match(css,/@media \(min-width:760px\) and \(max-width:1199px\)/);assert.match(css,/@media \(min-width:1200px\)/);assert.match(css,/@media \(min-width:1600px\)/);assert.match(css,/--touch-min:44px/);assert.match(css,/safe-area-inset/);});
check('ingest runtime identifies the current production release',()=>{const ingest=readFileSync(new URL('../src/ingest.mjs',import.meta.url),'utf8');assert.match(ingest,/APP_VERSION='1\.0\.0'/);});
if(errors.length){console.error(`\nContent audit failed (${errors.length}):\n- ${errors.join('\n- ')}`);process.exit(1)}
console.log(`\nContent audit passed: ${games.length} schedule rows, ${roster.length} current 53/reserve players, ${auditedPracticeSquad20260902.length} current practice-squad players, ${feed.length} sourced fallback feed items, ${visualArchive.length} audited visual assets.`);