import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { team, games, roster, feed, sources } from '../src/data.mjs';
import { auditedTeamContext } from '../src/team-context.mjs';
import { legacyTimeline, visualArchive, knownVisualsNotPictured, visualSources } from '../src/visual-audit.mjs';

const errors=[];
const check=(label,fn)=>{try{fn();console.log(`✓ ${label}`)}catch(error){errors.push(`${label}: ${error.message}`);console.error(`✗ ${label}`)}};
check('current team identity metadata',()=>{assert.equal(team.name,'Tennessee Titans');assert.equal(team.coach,'Robert Saleh');assert.equal(team.generalManager,'Mike Borgonzi');assert.equal(team.owner,'Amy Adams Strunk');assert.equal(team.president,'Burke Nihill');assert.deepEqual(team.colors,['Titans blue','red','white','navy blue']);assert.equal(team.primaryLogo,'The Shield');});
check('franchise milestone dates preserve 1959 vs 1960 distinction',()=>{assert.equal(team.franchiseGranted,'1959-08-14');assert.equal(team.firstSeason,1960);assert.equal(team.firstSeasonInTennessee,1997);assert.equal(team.firstSeasonAsTitans,1999);});
check('2026 schedule contains Week 9 bye',()=>{assert.ok(games.find(g=>g.week===9&&g.status==='bye'),'Week 9 bye is missing');});
check('Week 18 stays genuinely TBD at current Reliant Stadium name',()=>{const week18=games.find(g=>g.week===18&&g.opponentAbbr==='HOU');assert.ok(week18,'Week 18 at Houston is missing');assert.equal(week18.date,null);assert.equal(week18.dateTbd,true);assert.equal(week18.network,'TBD');assert.equal(week18.venue,'Reliant Stadium');});
check('preseason results and Bears broadcast are current through Aug. 24',()=>{const sea=games.find(g=>g.opponentAbbr==='SEA');assert.equal(sea.status,'final');assert.equal(sea.score,19);assert.equal(sea.opponentScore,16);const bears=games.find(g=>g.opponentAbbr==='CHI');assert.match(bears.network,/NFL Network/);assert.match(bears.network,/WKRN-TV News 2/);});
check('fallback roster reflects the Aug. 24 official transaction precedence',()=>{assert.equal(team.rosterCoverage.fallbackType,'cross-source-audited-snapshot');assert.equal(team.rosterCoverage.fallbackPlayers,roster.length);assert.equal(team.rosterCoverage.asOf,'2026-08-24');assert.match(team.rosterCoverage.sourceConflict,/Reid Carrico/i);assert.match(team.rosterCoverage.sourceConflict,/Milo Eifler/i);assert.equal(roster.length,96);assert.equal(roster.filter(p=>p.status==='Active').length,91);assert.equal(roster.filter(p=>p.status==='Reserve/Injured').length,5);assert.ok(roster.some(p=>p.name==='Reid Carrico'&&p.status==='Active'&&p.number===''));assert.ok(roster.some(p=>p.name==='Milo Eifler'&&p.number==='45'&&p.status==='Reserve/Injured'));assert.ok(roster.some(p=>p.name==='Tanoh Kpassagnon'&&p.number==='58'&&p.status==='Active'));assert.ok(roster.some(p=>p.name==='Nazeeh Johnson'&&p.status==='Reserve/Injured'));assert.equal(roster.some(p=>p.name==='Matt Lauter'),false);assert.equal(roster.some(p=>p.name==='Sean Brown'),false);assert.equal(roster.some(p=>p.name==='Dominic Richardson'),false);});
check('cross-source roster conflicts are explicit and freshness-aware',()=>{assert.equal(auditedTeamContext.auditedOn,'2026-08-24');const current=auditedTeamContext.knownConflicts.find(x=>/Reid Carrico/i.test(x.topic));assert.ok(current,'Aug. 24 Carrico/Eifler conflict is missing');assert.match(current.resolution,/newer dated Titans transaction/i);assert.match(auditedTeamContext.sourcePolicy.rule,/newer dated transaction/i);});
check('fallback player metadata avoids unsupported editorial tags',()=>{for(const player of roster)assert.equal('tag' in player,false,`${player.name} has an unsupported editorial tag`);});
check('Peter Skoronski fallback position matches official roster',()=>{assert.equal(roster.find(p=>p.name==='Peter Skoronski')?.position,'G');});
check('fallback feed carries the current Aug. 24 transaction and Seattle result',()=>{const move=feed.find(x=>/Reid Carrico/i.test(x.title));assert.ok(move);assert.match(move.url,/tennesseetitans\.com\/news\/titans-sign-lb-reid-carrico/);const game=feed.find(x=>/Titans 19, Seahawks 16/i.test(x.title));assert.ok(game);assert.match(game.url,/titans-seahawks-preseason-week-2-postgame-notes/);});
check('fallback feed contains sourceable links instead of placeholder social claims',()=>{assert.ok(feed.length>0);for(const item of feed){assert.match(item.url,/^https:\/\//,`${item.id} does not link to an external source`);assert.notEqual(item.source,'Reporter watchlist');}});
check('fallback source labels distinguish primary authorities from active persistence',()=>{assert.match(sources.find(s=>s.name==='NFLverse')?.status||'',/importer pending/i);assert.match(sources.find(s=>s.name==='NWS')?.status||'',/persistence pending/i);assert.match(sources.find(s=>s.name==='ESPN')?.purpose||'',/not authoritative roster or injury/i);assert.match(sources.find(s=>s.name==='Pro Football Reference')?.purpose||'',/cannot override official TBD/i);});
check('injury and staff semantics are current',()=>{assert.match(auditedTeamContext.injuryReport.status,/not-published-preseason/);assert.match(auditedTeamContext.injuryReport.detail,/regular season/i);assert.equal(auditedTeamContext.coachingUpdatedOn,'2026-08-24');assert.ok(auditedTeamContext.coaching.some(c=>c.name==='Brian Daboll'&&c.role==='Offensive Coordinator'));assert.ok(auditedTeamContext.coaching.some(c=>c.name==='Gus Bradley'&&c.role==='Defensive Coordinator'));});
check('visual labels are source-audited and active art avoids legacy aliases',()=>{assert.match(visualSources.wikipedia.url,/wikipedia\.org/);assert.match(visualSources.sportsLogos.url,/sportslogos\.net/);for(const item of visualArchive){assert.doesNotMatch(item.image,/\/assets\/legacy\//,`${item.id} uses an ambiguous legacy alias`);assert.ok(item.alt.length>=35,`${item.id} needs comprehensive alt text`);assert.ok(item.sourceKeys.length>=2,`${item.id} needs at least two source references`);}const uniform2018=legacyTimeline.find(x=>x.id==='2018-uniform-era');assert.match(uniform2018?.copy||'',/fireball-T remained the primary mark through 2025/i);assert.equal(visualArchive.some(item=>/Sword alternate|Vintage roundel/i.test(item.title)),false);const sword=knownVisualsNotPictured.find(item=>item.id==='titans-sword-alternate');assert.match(sword?.copy||'',/real Titans secondary\/alternate mark/i);});
check('base app no longer requests retired duplicate legacy assets',()=>{const app=readFileSync(new URL('../app.js',import.meta.url),'utf8');assert.doesNotMatch(app,/\/assets\/legacy\//);assert.doesNotMatch(app,/legacy-(?:banner|derrick|fireball|lightblue-wordmark|logo-evolution|sword|vintage-roundel|wordmark-fireball)\.webp/);});
check('responsive system has deliberate phone, tablet and desktop modes',()=>{const css=readFileSync(new URL('../viewport-polish-v101.css',import.meta.url),'utf8');assert.match(css,/@media \(max-width:759px\)/);assert.match(css,/@media \(min-width:760px\) and \(max-width:1199px\)/);assert.match(css,/@media \(min-width:1200px\)/);assert.match(css,/@media \(min-width:1600px\)/);assert.match(css,/--touch-min:44px/);assert.match(css,/safe-area-inset/);});
check('ingest runtime identifies the current production release',()=>{const ingest=readFileSync(new URL('../src/ingest.mjs',import.meta.url),'utf8');assert.match(ingest,/APP_VERSION='1\.0\.0'/);});
if(errors.length){console.error(`\nContent audit failed (${errors.length}):\n- ${errors.join('\n- ')}`);process.exit(1)}
console.log(`\nContent audit passed: ${games.length} schedule rows, ${roster.length} audited fallback players, ${feed.length} sourced fallback feed items, ${visualArchive.length} audited visual assets.`);
