import { getBootstrapData } from './db.mjs';
import { games as seedGames } from './data.mjs';
import { auditedRoster20260827, ROSTER_AUDIT_DATE } from './roster-audit-20260827.mjs';
import { auditedPreseasonGames, auditedPlayerPreseasonStats, auditedTeamPreseasonStats, auditedPreseasonSources, PRESEASON_GAMEBOOK_URL } from './preseason-p1-20260813.mjs';
import { auditedPreseasonGameP2, auditedPlayerPreseasonStatsP2, auditedPreseasonSourcesP2 } from './preseason-p2-20260823.mjs';
import { aggregatePlayerStats, aggregateTeamStats, buildLeaders, positionCounts } from './preseason-model.mjs';

const TEAM_ID='10',SEASON=2026,TIMEOUT=5500;
const signal=()=>typeof AbortSignal?.timeout==='function'?AbortSignal.timeout(TIMEOUT):undefined;
const norm=s=>String(s||'').toLowerCase().normalize('NFKD').replace(/[^a-z0-9 ]/g,'').replace(/\b(jr|sr|ii|iii|iv)\b/g,'').replace(/\s+/g,' ').trim();
const asArray=v=>Array.isArray(v)?v:[];
async function json(url){const r=await fetch(url,{headers:{'User-Agent':'TitansCommandCenter/1.0'},signal:signal()});if(!r.ok)throw new Error(`ESPN ${r.status}`);return r.json();}
function dbRoster(data){return asArray(data?.roster).map(p=>({id:String(p.id||''),name:p.name||p.full_name||'',number:String(p.number??p.jerseyNumber??''),position:p.position||'',unit:p.unit||'',status:p.status||'Current roster',experience:p.experience||'',headshot:''})).filter(p=>p.name);}
function isPreseasonEvent(e){return Number(e?.season?.type??e?.seasonType?.type??e?.seasonType)===1||/preseason/i.test(`${e?.seasonType?.name||''} ${e?.week?.text||''} ${e?.name||''}`)}
function completed(e){return Boolean(e?.status?.type?.completed)||/final/i.test(e?.status?.type?.name||e?.status?.type?.description||'')}
function parseTeamBox(summary,event){const team=asArray(summary?.boxscore?.players).find(x=>String(x?.team?.id)===TEAM_ID||/tennessee titans/i.test(x?.team?.displayName||''));if(!team)return [];const rows=[];for(const category of asArray(team.statistics)){const labels=asArray(category.labels),categoryName=category.displayName||category.name||'Stats';for(const entry of asArray(category.athletes)){const a=entry.athlete||{},values=asArray(entry.stats);rows.push({name:a.displayName||a.shortName||'',position:a.position?.abbreviation||'',category:categoryName,fields:labels.map((label,i)=>({label,value:String(values[i]??'')})),eventId:String(event.id),eventName:event.shortName||event.name||'',date:event.date||null,source:'ESPN public game summary'});}}return rows;}
const teamKey=name=>{const s=String(name||'').toLowerCase().replace(/[^a-z0-9]/g,'');if(/firstdown/.test(s))return'firstDowns';if(/thirddown/.test(s))return'thirdDown';if(/totalyard/.test(s))return'totalYards';if(/rushingyard/.test(s))return'rushingYards';if(/netpassingyard/.test(s)||/passingyard/.test(s))return'netPassingYards';if(/penalt/.test(s))return'penalties';if(/fumble/.test(s))return'fumbles';if(/touchdown/.test(s))return'touchdowns';if(/fieldgoal/.test(s))return'fieldGoals';if(/possession/.test(s))return'timeOfPossession';return null};
function parseTeamStats(summary){const team=asArray(summary?.boxscore?.teams).find(x=>String(x?.team?.id)===TEAM_ID||/tennessee titans/i.test(x?.team?.displayName||''));const out={};for(const item of asArray(team?.statistics)){const key=teamKey(item.name||item.label||item.displayName);if(key&&!out[key])out[key]=String(item.displayValue??item.value??'');}return out;}
function auditedRowsP1(){return Object.entries(auditedPlayerPreseasonStats).flatMap(([name,rows])=>rows.map(row=>({...row,name,source:'NFL official gamebook',sourceUrl:PRESEASON_GAMEBOOK_URL})));}
function auditedRowsP2(){return Object.entries(auditedPlayerPreseasonStatsP2).flatMap(([name,rows])=>rows.map(row=>({...row,name})));}
function sameDay(a,b){if(!a||!b)return false;return String(a).slice(0,10)===String(b).slice(0,10)}
function attach(roster,statRows){const byName=new Map();for(const row of statRows){const k=norm(row.name);if(!byName.has(k))byName.set(k,[]);byName.get(k).push(row)}const used=new Set();const players=roster.map(p=>{const k=norm(p.name),stats=byName.get(k)||[];if(stats.length)used.add(k);return {...p,stats,seasonStats:aggregatePlayerStats(stats)}});const other=[];for(const [k,stats] of byName){if(used.has(k))continue;const first=stats[0];other.push({name:first.name,position:first.position||'',number:'',unit:'Preseason participant',status:'Not matched to current roster',experience:'',stats,seasonStats:aggregatePlayerStats(stats)});}return {players,other};}
function scheduleRow(g,completedGames){const statsGame=completedGames.find(x=>sameDay(x.date,g.date)),seedFinal=/final/i.test(String(g.status||''));return {id:g.id,week:g.week,name:g.homeAway==='home'?`TEN vs ${g.opponentAbbr}`:`TEN @ ${g.opponentAbbr}`,opponent:g.opponent,opponentAbbr:g.opponentAbbr,date:g.date,status:statsGame?.status||g.status,completed:Boolean(statsGame)||seedFinal,statsAvailable:Boolean(statsGame),venue:g.venue||'',network:g.network||'',source:g.source||'Tennessee Titans'};}
function gameBookFromAuditP1(){const game=auditedPreseasonGames[0];return {...game,week:'P1',teamStats:{...auditedTeamPreseasonStats},teamStatsComplete:true,statRows:auditedRowsP1()};}
function gameBookFromAuditP2(){return {...auditedPreseasonGameP2,week:'P2',teamStats:{},teamStatsComplete:false,statRows:auditedRowsP2()};}
function coverageFor({roster,players,gameBooks,preseasonSchedule}){const completedSchedule=preseasonSchedule.filter(g=>g.completed),games=completedSchedule.map(g=>{const book=gameBooks.find(x=>sameDay(x.date,g.date));const statRows=asArray(book?.statRows);const teamFields=Object.keys(book?.teamStats||{}).length;return {id:g.id,week:g.week,name:g.name,date:g.date,statsAvailable:Boolean(book&&statRows.length),playerStatRows:statRows.length,teamStatFields:teamFields,teamStatsComplete:Boolean(book?.teamStatsComplete),source:book?.source||null,sourceScope:book?.sourceScope||null};});const playersWithStats=players.filter(p=>asArray(p.stats).length).length;return {completedGames:completedSchedule.length,completedGamesWithPlayerStats:games.filter(g=>g.statsAvailable).length,completedGamesMissingPlayerStats:games.filter(g=>!g.statsAvailable).length,completedGamesWithCompleteTeamStats:games.filter(g=>g.teamStatsComplete).length,games,rosterPlayers:roster.length,playersWithStats,playersWithoutStats:Math.max(0,players.length-playersWithStats),expectedLowBoxPositions:['C','G','T','OL','OT','OG','LS']};}

export async function preseasonStatsRoute(req,res,env=process.env){
  if(req.method!=='GET'){res.setHeader('Allow','GET');return res.status(405).json({ok:false,error:'Method not allowed'})}
  res.setHeader('Cache-Control','public, s-maxage=180, stale-while-revalidate=900');
  const diagnostics=[];let roster=auditedRoster20260827.map(x=>({...x,id:'',headshot:''})),rosterSource=`Tennessee Titans official roster + newer official transactions · audited ${ROSTER_AUDIT_DATE}`,rosterMode='audited-fallback';
  try{const db=await getBootstrapData(env);const live=db?.ok?dbRoster(db):[];if(live.length>=90){roster=live;rosterSource='Tennessee Titans official roster / transaction snapshot · latest audited database state';rosterMode='live-database';}else diagnostics.push(`Live roster database unavailable; serving the dated ${auditedRoster20260827.length}-player ${ROSTER_AUDIT_DATE} audited roster snapshot.`);}catch{diagnostics.push(`Live roster database unavailable; serving the dated ${auditedRoster20260827.length}-player ${ROSTER_AUDIT_DATE} audited roster snapshot.`);}
  const gameBooks=[gameBookFromAuditP1(),gameBookFromAuditP2()];let liveAdded=0,liveMisses=0;
  try{const schedule=await json(`https://site.api.espn.com/apis/site/v2/sports/football/nfl/teams/${TEAM_ID}/schedule?season=${SEASON}`);const liveEvents=asArray(schedule.events).filter(isPreseasonEvent).filter(completed).sort((a,b)=>new Date(a.date)-new Date(b.date));for(const event of liveEvents){if(gameBooks.some(g=>sameDay(g.date,event.date)))continue;try{const summary=await json(`https://site.api.espn.com/apis/site/v2/sports/football/nfl/summary?event=${encodeURIComponent(event.id)}`),statRows=parseTeamBox(summary,event),teamStats=parseTeamStats(summary,event);if(statRows.length){gameBooks.push({id:String(event.id),week:`P${gameBooks.length+1}`,name:event.shortName||event.name,date:event.date,status:event.status?.type?.shortDetail||'Final',opponent:'',source:'ESPN public game summary',sourceUrl:`https://www.espn.com/nfl/game/_/gameId/${event.id}`,sourceScope:'Public ESPN player and team box-score fields returned for this completed event.',teamStats,teamStatsComplete:Boolean(Object.keys(teamStats).length>=8),statRows});liveAdded++;}else liveMisses++;}catch{liveMisses++;}}}catch{diagnostics.push('ESPN server-side feed is currently unavailable in this hosting environment; official audited gamebook data remains active.');}
  gameBooks.sort((a,b)=>new Date(a.date)-new Date(b.date));
  const allRows=gameBooks.flatMap(g=>g.statRows||[]),linked=attach(roster,allRows),completedGames=gameBooks.map(({statRows,teamStats,...g})=>g),teamStatsByGame=Object.fromEntries(gameBooks.map(g=>[g.id,g.teamStats||{}])),completeTeamBooks=gameBooks.filter(g=>g.teamStatsComplete&&Object.keys(g.teamStats||{}).length),allTeamStatsComplete=completeTeamBooks.length===gameBooks.length,seasonTeamStats=allTeamStatsComplete?aggregateTeamStats(completeTeamBooks.map(g=>g.teamStats||{})):{},preseasonSchedule=seedGames.filter(g=>String(g.week).startsWith('P')).map(g=>scheduleRow(g,completedGames)),nextGame=preseasonSchedule.find(g=>!g.completed&&g.status!=='final')||null,sources=[...auditedPreseasonSources,...auditedPreseasonSourcesP2],coverage=coverageFor({roster,players:linked.players,gameBooks,preseasonSchedule});
  if(liveAdded)sources.push({label:'ESPN public game summaries · newly completed preseason games',url:'https://www.espn.com/nfl/team/schedule/_/name/ten/season/2026'});
  if(coverage.completedGamesMissingPlayerStats){diagnostics.push(`${coverage.completedGamesMissingPlayerStats} completed preseason game${coverage.completedGamesMissingPlayerStats===1?' is':'s are'} missing player box-score detail from the current upstream stat source.`);}
  if(!allTeamStatsComplete)diagnostics.push('Season team-stat totals are withheld because at least one completed preseason source does not expose the full team-stat table.');
  if(liveMisses&&!coverage.completedGamesMissingPlayerStats)diagnostics.push('A completed ESPN preseason event was reachable without usable Tennessee player-stat rows; audited official player coverage remains active for known completed games.');
  const auditedStatsSource='NFL official P1 gamebook + Tennessee Titans official P2 Game Center/postgame notes';
  const statsSource=liveAdded?`${auditedStatsSource} + ESPN public summaries for later completed games`:auditedStatsSource;
  return res.status(200).json({ok:true,season:SEASON,seasonType:'preseason',rosterSource,rosterMode,statsSource,rosterCount:linked.players.length,completedGames,preseasonSchedule,nextGame,teamStatsByGame,seasonTeamStats,teamStats:seasonTeamStats,teamStatsComplete:allTeamStatsComplete,positionCounts:positionCounts(linked.players),leaders:buildLeaders(linked.players),players:linked.players,otherParticipants:linked.other,coverage,sources,diagnostics,dataMode:liveAdded?'audited-plus-live':'audited-fallback',fetchedAt:new Date().toISOString()});
}