export const auditedTeamContext = {
  auditedOn:'2026-08-24',
  sourcePolicy:{
    currentTeamData:['Tennessee Titans','NFL.com'],franchiseHistory:['Tennessee Titans','Pro Football Hall of Fame'],statisticalCrossCheck:['Tennessee Titans team stats','NFL.com','Pro Football Reference','nflverse'],visualCrossCheck:['Tennessee Titans brand/history','SportsLogos.net'],secondaryContext:['Wikipedia'],
    rule:'Use a domain-specific and fact-specific source hierarchy. Current official Titans/NFL information overrides secondary sources when they conflict. Within the same official tier, the newer dated transaction/news item can outrank a roster page that has not propagated the move yet. Conflicting source values are retained as audit notes instead of silently blended.',
    domains:[
      {key:'roster-schedule-transactions',label:'Roster · Schedule · Transactions',primary:'Tennessee Titans official',crossCheck:'NFL.com',secondary:'nflverse',note:'Dated official transactions control same-day roster moves. Never infer missing kickoff times, roster moves, jersey numbers, or statuses from secondary templates.'},
      {key:'coaching-leadership',label:'Coaching · Leadership',primary:'Tennessee Titans official',crossCheck:'NFL.com when available',secondary:'Reference sources only',note:'Official current titles control.'},
      {key:'statistics',label:'Statistics',primary:'Tennessee Titans structured team stats / official postgame notes',crossCheck:'NFL.com · Pro Football Reference',secondary:'nflverse',note:'Structured stat tables control over editorial recap copy when official pages disagree. Partial postgame-note snapshots are labeled as partial.'},
      {key:'injuries',label:'Injuries',primary:'Tennessee Titans official injury report',crossCheck:'NFL.com',secondary:'Roster Reserve/Injured is a separate status',note:'No published report is not the same thing as zero injuries. The Titans state weekly injury reports begin in the regular season.'},
      {key:'history',label:'Franchise History',primary:'Tennessee Titans history',crossCheck:'Pro Football Hall of Fame',secondary:'Wikipedia · Pro Football Reference',note:'Preserve nuance such as franchise grant date versus first season.'},
      {key:'visuals',label:'Logos · Uniforms · Visuals',primary:'Tennessee Titans brand/history',crossCheck:'SportsLogos.net',secondary:'User-supplied reference art',note:'Only an exact verified mark receives an exact era/title label. Representative art stays labeled representative.'}
    ]
  },
  knownConflicts:[
    {topic:'Reid Carrico / Milo Eifler roster status · Aug. 24 audit',officialValue:'Titans Aug. 24 transaction: Reid Carrico signed; Milo Eifler placed on Injured Reserve',secondaryValue:'The official roster page crawl still showed the pre-transaction state',resolution:'Use the newer dated Titans transaction until the roster page catches up. Carrico is active with no guessed jersey number; Eifler is Reserve/Injured.'},
    {topic:'Sean Brown current roster status · Aug. 22 audit',officialValue:'Tennessee Titans Aug. 17 transaction: waived/injured',secondaryValue:'NFL.com roster still lists Sean Brown as reserve',resolution:'Exclude Sean Brown from the current audited roster. The dated Titans transaction controls over a stale secondary roster listing.'},
    {topic:'2026 preseason opener date',officialValue:'Aug. 13, 2026',secondaryValue:'Pro Football Reference currently lists Aug. 15',resolution:'Use Tennessee Titans/NFL schedule: Aug. 13.'},
    {topic:'Bears preseason broadcast',officialValue:'Current Titans schedule lists NFL Network; Titans preseason announcement lists WKRN-TV News 2/regional affiliates',secondaryValue:'A single-network label can hide either the national or local carriage',resolution:'Display both when space allows: NFL Network / WKRN-TV News 2 (regional).'},
    {topic:'Franchise origin date',officialValue:'Franchise granted Aug. 14, 1959; first season 1960',secondaryValue:'Some team/league summaries simply say established 1960',resolution:'Display both grant date and first season instead of collapsing them.'},
    {topic:'Jeffery Simmons 2025 total tackles',officialValue:'67 total tackles (Tennessee Titans structured team stats)',secondaryValue:'NFL.com individual career page currently shows 65',resolution:'Use 67: Tennessee Titans official team stats, an official Titans contract article, and Pro Football Reference agree; retain the NFL.com discrepancy as an audit note.'},
    {topic:'Cedric Gray 2025 total tackles',officialValue:'164 total tackles (Tennessee Titans structured team stats)',secondaryValue:'A Jan. 7, 2026 Titans editorial recap says 160',resolution:'Use 164 from the official structured team-stat table; retain the editorial discrepancy instead of blending the values.'},
    {topic:'Mario Goodrich III identity in Aug. 1 transaction',officialValue:'Official roster and Titans news: Mario Goodrich III',secondaryValue:'Official transaction table currently says Mario Goodson III',resolution:'Use Mario Goodrich III for the player identity because the current official roster and the dedicated Titans signing story agree; retain the transaction-table typo as an audit note.'}
  ],
  leadershipSourceUrl:'https://www.tennesseetitans.com/team/front-office-roster/',
  leadership:[{role:'Controlling Owner/Co-Chairman, Board of Directors',name:'Amy Adams Strunk'},{role:'General Manager',name:'Mike Borgonzi'},{role:'President and Chief Executive Officer',name:'Burke Nihill'}],
  coachingSourceUrl:'https://www.tennesseetitans.com/team/coaches-roster/',coachingUpdatedOn:'2026-08-24',
  coaching:[
    {unit:'Team',role:'Head Coach',name:'Robert Saleh'},{unit:'Team',role:'Chief of Staff',name:'Rob Dadona'},
    {unit:'Offense',role:'Offensive Coordinator',name:'Brian Daboll'},{unit:'Offense',role:'Offensive Line',name:'Carmen Bricillo'},{unit:'Offense',role:'Offensive Assistant',name:'Trevor Browder'},{unit:'Offense',role:'Running Backs/Bill Walsh Diversity Coaching Fellowship Coordinator',name:'Randy Jordan'},{unit:'Offense',role:'Offensive Assistant/Game Management',name:'Cade Knox'},{unit:'Offense',role:'Wide Receivers',name:'Greg Lewis'},{unit:'Offense',role:'Offensive Assistant',name:'John Rudnicki'},{unit:'Offense',role:'Tight Ends',name:'Luke Stocker'},{unit:'Offense',role:'Quarterbacks',name:'Shea Tierney'},{unit:'Offense',role:'Assistant Offensive Line',name:'Isaac Williams'},
    {unit:'Defense',role:'Defensive Coordinator',name:'Gus Bradley'},{unit:'Defense',role:'Senior Defensive Assistant',name:'Ben Bloom'},{unit:'Defense',role:'Linebackers',name:'Dave Borgonzi'},{unit:'Defense',role:'Defensive Backs/Nickels',name:'Dalton Hilliard'},{unit:'Defense',role:'Defensive Backs/Safeties',name:'Marquand Manuel'},{unit:'Defense',role:'Defensive Pass Game Coordinator/Cornerbacks',name:'Tony Oden'},{unit:'Defense',role:'Defensive Assistant',name:'Ahmed Saleh'},{unit:'Defense',role:'Assistant Defensive Line',name:'Tanzel Smart'},{unit:'Defense',role:'Defensive Run Game Coordinator/Defensive Line',name:'Aaron Whitecotton'},
    {unit:'Special Teams',role:'Assistant Head Coach/Special Teams Coordinator',name:'John Fassel'},{unit:'Special Teams',role:'Assistant Special Teams',name:'Rayna Stewart'}
  ],
  injuryReport:{status:'not-published-preseason',label:'Official weekly injury report not yet published',detail:'The Titans state that injury reports become available in the regular season. Reserve/Injured roster status is tracked separately and should not be presented as the weekly injury report.',sourceUrl:'https://www.tennesseetitans.com/team/injury-report/'},
  baselineStats:{season:2025,label:'2025 verified baseline — not 2026 stats',sourceLabel:'Tennessee Titans official 2025 team statistics',sourceUrl:'https://www.tennesseetitans.com/team/stats/2025/REG',players:[
    {name:'Cam Ward',position:'QB',lines:['323/540 passing','3,169 pass yds','15 TD · 7 INT','80.2 rating'],sourceUrl:'https://www.tennesseetitans.com/team/stats/2025/REG'},
    {name:'Tony Pollard',position:'RB',lines:['242 rush att','1,082 rush yds','4.5 yds/att','5 rush TD'],sourceUrl:'https://www.tennesseetitans.com/team/stats/2025/REG'},
    {name:'Jeffery Simmons',position:'DT',lines:['15 games','67 total tackles','11 sacks','1 safety'],sourceUrl:'https://www.tennesseetitans.com/team/stats/2025/REG'}
  ]},
  visualAudit:{rule:'Only the current Shield is treated as the current primary mark. Historical archive images are labeled as representative/reference visuals unless the exact year variant is verified.',currentPrimary:'The Shield',auditedOn:'2026-08-24',sources:['https://www.tennesseetitans.com/brand/','https://www.tennesseetitans.com/history/logo-history','https://www.sportslogos.net/logos/list_by_team/160/Tennessee-Titans-Logos/']}
};
export async function getAuditedTeamContext(sql){if(!sql)return {...auditedTeamContext,depthChart:{status:'database-unavailable',rows:[]}};const rows=await sql`with latest_snapshot as (select max(d.captured_at) captured_at from depth_chart_snapshots d join teams t on t.id=d.team_id join sources s on s.id=d.source_id where t.abbreviation='TEN' and s.slug='titans'), latest_roster as (select rs.player_id,rs.jersey_number,row_number() over(partition by rs.player_id order by rs.captured_at desc,rs.id desc) rn from roster_snapshots rs join teams t on t.id=rs.team_id where t.abbreviation='TEN') select d.position_group,d.position,d.slot,d.rank,d.captured_at,d.raw_payload,p.id player_id,p.full_name,lr.jersey_number from depth_chart_snapshots d join latest_snapshot x on x.captured_at=d.captured_at join teams t on t.id=d.team_id and t.abbreviation='TEN' join sources s on s.id=d.source_id and s.slug='titans' join players p on p.id=d.player_id left join latest_roster lr on lr.player_id=p.id and lr.rn=1 order by case d.position_group when 'Offense' then 1 when 'Defense' then 2 when 'Special Teams' then 3 else 4 end,d.slot,d.rank,p.full_name`;const first=rows[0];return {...auditedTeamContext,depthChart:{status:rows.length?'available':'awaiting-official-snapshot',unofficial:true,source:'Tennessee Titans',sourceUrl:first?.raw_payload?.source_url||'https://www.tennesseetitans.com/team/depth-chart',sourceDate:first?.raw_payload?.source_date||null,capturedAt:first?.captured_at?new Date(first.captured_at).toISOString():null,rows:rows.map(r=>({unit:r.position_group,position:r.position,slot:Number(r.slot),rank:Number(r.rank),playerId:String(r.player_id),name:r.full_name,number:r.jersey_number||''}))}};}
