import { requireAdminAuth, requireIngestAuth, syncTitansOfficialAudit, syncBluesky, syncEspn, syncNflverseRoster, syncNflverseStats, syncNwsNextHomeGame, syncFreeOdds, summarizeRefreshResults, recordSyncRun } from '../src/ingest.mjs';
import { fetchFreeOdds, probeFreeOddsProviders } from '../src/odds.mjs';
import { preseasonStatsRoute } from '../src/preseason-api.mjs';
import { marketDataRoute } from '../src/market-api.mjs';
import { advancedAnalyticsRoute } from '../src/advanced-analytics-api.mjs';

const APP_VERSION='1.0.0';
const TITANS_QUERY='Tennessee Titans';
let oddsCache={expiresAt:0,value:null,inflight:null};
const runtimeEnv=env=>env||process.env;
const oddsCacheSeconds=env=>{const requested=Number(runtimeEnv(env).ODDS_CACHE_SECONDS||300);return Number.isFinite(requested)?Math.max(300,Math.min(900,requested)):300;};
const routeOf=req=>String(req.query?.route||'').trim().replace(/^\/+|\/+$/g,'');
const queryOf=req=>Object.fromEntries(Object.entries(req.query||{}).filter(([key])=>key!=='route'));
function methodOnly(req,res,allowed){res.setHeader('Allow',allowed);if(req.method!==allowed){res.status(405).json({ok:false,error:'Method not allowed'});return true}return false}
async function retiredWarehouseRoute(req,res){if(methodOnly(req,res,'GET'))return;res.setHeader('Cache-Control','no-store');return res.status(503).json({ok:false,configured:false,code:'WAREHOUSE_ROUTE_RETIRED',route:routeOf(req),error:'Legacy warehouse route retired. Titans Command Center production data is served by the Cloudflare D1 Worker.'});}
async function espnRoute(req,res){if(methodOnly(req,res,'GET'))return;res.setHeader('Cache-Control','s-maxage=30, stale-while-revalidate=60');try{const upstream=await fetch('https://site.api.espn.com/apis/site/v2/sports/football/nfl/scoreboard',{headers:{'User-Agent':`TitansCommandCenter/${APP_VERSION}`},signal:AbortSignal.timeout(4500)});if(!upstream.ok)throw new Error(`ESPN ${upstream.status}`);return res.status(200).json({ok:true,provider:'ESPN',unofficial:true,fetchedAt:new Date().toISOString(),payload:await upstream.json()});}catch(error){console.error('[espn-scoreboard]',error);return res.status(502).json({ok:false,provider:'ESPN',unofficial:true,error:'Live scoreboard provider unavailable'});}}
async function blueskyRoute(req,res){if(methodOnly(req,res,'GET'))return;const query=queryOf(req),q=String(query.q||TITANS_QUERY).slice(0,120),rawLimit=Number(query.limit||20),limit=Number.isFinite(rawLimit)?Math.min(50,Math.max(1,Math.trunc(rawLimit))):20,url=new URL('https://public.api.bsky.app/xrpc/app.bsky.feed.searchPosts');url.searchParams.set('q',q);url.searchParams.set('limit',String(limit));url.searchParams.set('sort','latest');try{const upstream=await fetch(url,{signal:AbortSignal.timeout(5000)});if(!upstream.ok)throw new Error(`Bluesky ${upstream.status}`);const data=await upstream.json(),items=(data.posts||[]).map(post=>{const text=post.record?.text||'',rkey=String(post.uri||'').split('/').pop(),handle=post.author?.handle||post.author?.displayName||'Bluesky user';return {id:`bsky:${post.uri}`,type:'social',tier:'community',source:`@${handle} · Bluesky`,title:text.length>110?`${text.slice(0,107)}…`:text||'Bluesky post',summary:`${post.likeCount||0} likes · ${post.repostCount||0} reposts · ${post.replyCount||0} replies`,publishedAt:post.record?.createdAt||post.indexedAt,topics:['social','bluesky'],url:post.author?.handle&&rkey?`https://bsky.app/profile/${post.author.handle}/post/${rkey}`:'https://bsky.app/'};});res.setHeader('Cache-Control','s-maxage=30, stale-while-revalidate=60');return res.status(200).json({ok:true,provider:'Bluesky',query:q,items});}catch(error){console.error('[bluesky-search]',error);return res.status(502).json({ok:false,provider:'Bluesky',query:q,error:'Bluesky search unavailable'});}}
async function oddsRoute(req,res,env){env=runtimeEnv(env);if(methodOnly(req,res,'GET'))return;if(Object.keys(queryOf(req)).length){res.setHeader('Cache-Control','no-store');return res.status(400).json({ok:false,error:'Public odds endpoint does not accept query parameters'});}const cacheSeconds=oddsCacheSeconds(env),now=Date.now();if(oddsCache.value&&now<oddsCache.expiresAt){res.setHeader('Cache-Control',`public, s-maxage=${cacheSeconds}, stale-while-revalidate=300`);return res.status(200).json({...oddsCache.value,cache:'memory'});}try{if(!oddsCache.inflight)oddsCache.inflight=fetchFreeOdds(env,{live:null,compare:false,includePeriods:false,includePlayerProps:true,includeFutures:true,maxEvents:2}).finally(()=>{oddsCache.inflight=null});const data=await oddsCache.inflight;if(!data.ok){res.setHeader('Cache-Control','public, s-maxage=60, stale-while-revalidate=120');return res.status(503).json(data)}oddsCache.value=data;oddsCache.expiresAt=Date.now()+cacheSeconds*1000;res.setHeader('Cache-Control',`public, s-maxage=${cacheSeconds}, stale-while-revalidate=300`);return res.status(200).json({...data,cache:'miss'});}catch(error){console.error('[odds]',error);res.setHeader('Cache-Control','public, s-maxage=30, stale-while-revalidate=60');return res.status(502).json({ok:false,provider:'free-odds-stack',error:'Odds providers unavailable'});}}
async function providerHealthRoute(req,res,env){env=runtimeEnv(env);if(methodOnly(req,res,'GET'))return;res.setHeader('Cache-Control','no-store');const auth=requireAdminAuth(req,env);if(!auth.ok)return res.status(auth.status).json(auth);const result=await probeFreeOddsProviders(env,{compare:queryOf(req).compare!=='false'});return res.status(result.ok?200:503).json(result);}
const syncJobs=env=>({'official-audit':()=>syncTitansOfficialAudit(env),espn:()=>syncEspn(env),bluesky:()=>syncBluesky(env,TITANS_QUERY,30),'nflverse-roster':()=>syncNflverseRoster(env,2026),'nflverse-stats':()=>syncNflverseStats(env,2026),'nws-weather':()=>syncNwsNextHomeGame(env),odds:()=>syncFreeOdds(env)});
async function executeJob(job,run,env){const started=new Date();let result;try{result={job,...(await run())};}catch(error){console.error('[source-check]',job,error);result={job,ok:false,error:'Sync job failed'};}const stored=await recordSyncRun(env,job,result,started);return {...result,auditStored:Boolean(stored.stored)};}
async function syncRoute(req,res,env){env=runtimeEnv(env);if(methodOnly(req,res,'POST'))return;res.setHeader('Cache-Control','no-store');const auth=requireIngestAuth(req,env);if(!auth.ok)return res.status(auth.status).json(auth);const jobs=syncJobs(env),requested=String(queryOf(req).job||'').trim();if(!requested)return res.status(400).json({ok:false,error:'job query parameter is required',availableJobs:Object.keys(jobs)});const selected=requested.split(',').map(v=>v.trim()).filter(Boolean),invalid=selected.filter(job=>!jobs[job]);if(invalid.length)return res.status(400).json({ok:false,error:`Unknown job(s): ${invalid.join(', ')}`,availableJobs:Object.keys(jobs)});const results=[];for(const job of selected)results.push(await executeJob(job,jobs[job],env));const summary=summarizeRefreshResults(results),status=summary.succeeded>0?200:summary.skipped>0&&summary.failed===0?202:502;return res.status(status).json({...summary,mode:'manual-source-check',fetchedAt:new Date().toISOString(),results});}
async function cronRoute(req,res,env){env=runtimeEnv(env);if(methodOnly(req,res,'GET'))return;res.setHeader('Cache-Control','no-store');const auth=requireIngestAuth(req,env);if(!auth.ok)return res.status(auth.status).json(auth);const configured=syncJobs(env),jobs=[['official-audit',configured['official-audit']],['espn',configured.espn],['nflverse-roster',configured['nflverse-roster']],['nflverse-stats',configured['nflverse-stats']],['nws-weather',configured['nws-weather']],['bluesky',configured.bluesky],['odds',()=>env.PROPLINE_API_KEY||env.ODDS_API_IO_KEY?configured.odds():Promise.resolve({ok:true,skipped:true,source:'titans-cc',error:'No free odds API key configured'})]],results=await Promise.all(jobs.map(([job,run])=>executeJob(job,run,env))),summary=summarizeRefreshResults(results);return res.status(summary.succeeded>0?200:502).json({...summary,mode:'daily-source-check',fetchedAt:new Date().toISOString(),results});}
const routes=new Map([['health',retiredWarehouseRoute],['data',retiredWarehouseRoute],['analytics',retiredWarehouseRoute],['advanced-analytics',(req,res,env)=>advancedAnalyticsRoute(req,res,runtimeEnv(env))],['player',retiredWarehouseRoute],['preseason-stats',(req,res,env)=>preseasonStatsRoute(req,res,runtimeEnv(env))],['market-data',(req,res,env)=>marketDataRoute(req,res,runtimeEnv(env))],['espn-scoreboard',espnRoute],['bluesky-search',blueskyRoute],['odds',oddsRoute],['provider-health',providerHealthRoute],['sync',syncRoute],['cron-refresh',cronRoute]]);
export default async function handler(req,res,env=process.env){const route=routeOf(req),run=routes.get(route);if(!run)return res.status(404).json({ok:false,error:'Unknown API route'});try{return await run(req,res,env)}catch(error){console.error('[api-gateway]',route,error);return res.status(500).json({ok:false,error:'API request failed'});}}
