import { fetchFreeOdds } from '../src/odds.mjs';
const TIMEOUT=6000,SPREAD_URL='https://thespread.azureedge.net/odds/nfl.json',REF_URL='https://www.busr.ag/?p=102015',NFL_SCHEDULE='https://www.nfl.com/schedules/2026/by-team/tennessee-titans';
const sig=()=>typeof AbortSignal?.timeout==='function'?AbortSignal.timeout(TIMEOUT):undefined;
async function json(url){const r=await fetch(url,{headers:{'User-Agent':'TitansCommandCenter/0.7','Accept':'application/json'},signal:sig()});if(!r.ok)throw new Error(`${new URL(url).hostname} ${r.status}`);return r.json()}
const val=s=>{const m=String(s||'').match(/([+-]?\d+(?:\.\d+)?)(?!.*[+-]?\d)/);return m?Number(m[1]):null};
const price=s=>{const m=String(s||'').match(/\(([+-]?\d+)\)|\s([+-]\d+)\s*$/);return m?Number(m[1]||m[2]):null};
function spreadRows(payload){const rows=[],events=[];for(const e of Array.isArray(payload)?payload:[]){if(!/tennessee|titans|\bten\b/i.test(e.Event||''))continue;events.push({id:`spread-${e.Date}`,name:e.Event,date:e.Date,status:'Upcoming',source:'TheSpread.io'});for(const o of e.Odds||[]){const base={provider:'TheSpread.io',book:o.Source||'Sportsbook',eventName:e.Event,eventDate:e.Date,category:'game_line',reference:false,available:true,capturedAt:new Date().toISOString(),sourceUrl:SPREAD_URL};for(const [key,label,side] of [['Team1Spread','Spread','Team 1'],['Team2Spread','Spread','Team 2'],['Team1Money','Moneyline','Team 1'],['Team2Money','Moneyline','Team 2']]){if(o[key])rows.push({...base,providerOddId:`${e.Date}|${o.Source}|${key}`,marketName:label,side:String(o[key]).split(' ')[0]||side,line:label==='Spread'?val(o[key]):null,price:label==='Moneyline'?val(o[key]):price(o[key])});}if(o.OverUnder){const [total,juice='']=String(o.OverUnder).split(/\s+/,2),[overPrice,underPrice]=juice.split('/').map(Number);rows.push({...base,providerOddId:`${e.Date}|${o.Source}|over`,marketName:'Total',side:'Over',line:Number(total),price:Number.isFinite(overPrice)?overPrice:null});rows.push({...base,providerOddId:`${e.Date}|${o.Source}|under`,marketName:'Total',side:'Under',line:Number(total),price:Number.isFinite(underPrice)?underPrice:null});}}}return {events,odds:rows};}
function publicReference(){const event={id:'2026-p2-sea-ten',name:'Seattle Seahawks at Tennessee Titans',date:'2026-08-24T00:00:00Z',status:'Sun Aug. 23 · 8:00 PM ET · FOX',source:'NFL schedule',sourceUrl:NFL_SCHEDULE};const base={provider:'BUSR preseason board',book:'BUSR reference',eventName:event.name,eventDate:event.date,category:'game_line',reference:true,available:false,capturedAt:'2026-08-19T00:00:00Z',sourceUrl:REF_URL};return {events:[event],odds:[{...base,providerOddId:'ref-sea-spread',marketName:'Spread',side:'SEA',line:-1.5,price:null},{...base,providerOddId:'ref-ten-spread',marketName:'Spread',side:'TEN',line:1.5,price:null},{...base,providerOddId:'ref-sea-ml',marketName:'Moneyline',side:'SEA',line:null,price:-125},{...base,providerOddId:'ref-ten-ml',marketName:'Moneyline',side:'TEN',line:null,price:105},{...base,providerOddId:'ref-over',marketName:'Total',side:'Over',line:36.5,price:-110},{...base,providerOddId:'ref-under',marketName:'Total',side:'Under',line:36.5,price:-110}]};}
export default async function handler(req,res){
  if(req.method!=='GET'){res.setHeader('Allow','GET');return res.status(405).json({ok:false,error:'Method not allowed'})}
  res.setHeader('Cache-Control','public, s-maxage=180, stale-while-revalidate=600');const diagnostics=[];
  try{const configured=await fetchFreeOdds(process.env,{maxEvents:3});if(configured.ok&&(configured.odds?.length||configured.events?.length))return res.status(200).json({...configured,propsAvailable:true,sourceMode:'configured-provider',message:'Live configured provider data.'});}catch(e){diagnostics.push(`Configured provider: ${e.message}`)}
  try{const parsed=spreadRows(await json(SPREAD_URL));if(parsed.odds.length)return res.status(200).json({ok:true,provider:'TheSpread.io keyless feed',events:parsed.events,odds:parsed.odds,futures:[],propsAvailable:false,sourceMode:'keyless-live',message:'Keyless game-line feed loaded. Player props require a configured props provider.',diagnostics,fetchedAt:new Date().toISOString()});diagnostics.push('TheSpread.io returned no current Titans rows.');}catch(e){diagnostics.push(`TheSpread.io: ${e.message}`)}
  const ref=publicReference();return res.status(200).json({ok:true,provider:'Public reference snapshot',events:ref.events,odds:ref.odds,futures:[],propsAvailable:false,sourceMode:'reference-snapshot',message:'No verified live provider is configured, so this board shows a clearly labeled public preseason reference snapshot instead of failing. Refresh retries live providers first.',diagnostics,referenceNotice:'Reference odds are not guaranteed current. BUSR preseason board listed SEA -1.5 / -125, TEN +1.5 / +105, total 36.5. Check a live sportsbook before relying on a line.',sources:[{label:'BUSR preseason board',url:REF_URL},{label:'NFL official Titans schedule',url:NFL_SCHEDULE}],fetchedAt:new Date().toISOString()});
}
