import { fetchFreeOdds } from '../src/odds.mjs';
const TIMEOUT=6000,SPREAD_URL='https://thespread.azureedge.net/odds/nfl.json',BUSR_URL='https://www.busr.ag/news/nfl/nfl-odds-for-all-preseason-week-2-games',NFL_SCHEDULE='https://www.nfl.com/schedules/2026/by-team/tennessee-titans',KICKOFF='2026-08-24T00:00:00Z';
const sig=()=>typeof AbortSignal?.timeout==='function'?AbortSignal.timeout(TIMEOUT):undefined;
async function fetchOk(url,accept='*/*'){const r=await fetch(url,{headers:{'User-Agent':'TitansCommandCenter/0.8','Accept':accept},signal:sig()});if(!r.ok)throw new Error(`${new URL(url).hostname} ${r.status}`);return r}
async function json(url){return (await fetchOk(url,'application/json')).json()}
const val=s=>{const m=String(s||'').match(/([+-]?\d+(?:\.\d+)?)(?!.*[+-]?\d)/);return m?Number(m[1]):null};
const price=s=>{const m=String(s||'').match(/\(([+-]?\d+)\)|\s([+-]\d+)\s*$/);return m?Number(m[1]||m[2]):null};
function spreadRows(payload){const rows=[],events=[];for(const e of Array.isArray(payload)?payload:[]){if(!/tennessee|titans|\bten\b/i.test(e.Event||''))continue;events.push({id:`spread-${e.Date}`,name:e.Event,date:e.Date,status:'Upcoming',source:'TheSpread.io'});for(const o of e.Odds||[]){const base={provider:'TheSpread.io',book:o.Source||'Sportsbook',eventName:e.Event,eventDate:e.Date,category:'game_line',reference:false,available:true,capturedAt:new Date().toISOString(),sourceUrl:SPREAD_URL};for(const [key,label,side] of [['Team1Spread','Spread','Team 1'],['Team2Spread','Spread','Team 2'],['Team1Money','Moneyline','Team 1'],['Team2Money','Moneyline','Team 2']]){if(o[key])rows.push({...base,providerOddId:`${e.Date}|${o.Source}|${key}`,marketName:label,side:String(o[key]).split(' ')[0]||side,line:label==='Spread'?val(o[key]):null,price:label==='Moneyline'?val(o[key]):price(o[key])});}if(o.OverUnder){const [total,juice='']=String(o.OverUnder).split(/\s+/,2),[overPrice,underPrice]=juice.split('/').map(Number);rows.push({...base,providerOddId:`${e.Date}|${o.Source}|over`,marketName:'Total',side:'Over',line:Number(total),price:Number.isFinite(overPrice)?overPrice:null});rows.push({...base,providerOddId:`${e.Date}|${o.Source}|under`,marketName:'Total',side:'Under',line:Number(total),price:Number.isFinite(underPrice)?underPrice:null});}}}return {events,odds:rows};}
function busrRows({spread=-2.5,seahawksMl=-140,titansMl=120,total=37.5,capturedAt='2026-08-18T00:00:00Z'}={}){const event={id:'2026-p2-sea-ten',name:'Seattle Seahawks at Tennessee Titans',date:KICKOFF,status:'Sun Aug. 23 · 8:00 PM ET · FOX',source:'NFL schedule',sourceUrl:NFL_SCHEDULE};const base={provider:'BUSR Week 2 published lines',book:'Published reference',eventName:event.name,eventDate:event.date,category:'game_line',reference:true,available:false,capturedAt,sourceUrl:BUSR_URL};return {events:[event],odds:[{...base,providerOddId:'busr-sea-spread',marketName:'Spread',side:'SEA',line:spread,price:null},{...base,providerOddId:'busr-ten-spread',marketName:'Spread',side:'TEN',line:-spread,price:null},{...base,providerOddId:'busr-sea-ml',marketName:'Moneyline',side:'SEA',line:null,price:seahawksMl},{...base,providerOddId:'busr-ten-ml',marketName:'Moneyline',side:'TEN',line:null,price:titansMl},{...base,providerOddId:'busr-over',marketName:'Total',side:'Over',line:total,price:null},{...base,providerOddId:'busr-under',marketName:'Total',side:'Under',line:total,price:null}]};}
async function busrPublishedReference(){const text=await (await fetchOk(BUSR_URL,'text/html')).text(),start=text.search(/Seattle Seahawks vs\. Tennessee Titans/i);if(start<0)throw new Error('Titans matchup not found');const chunk=text.slice(start,start+9000).replace(/<[^>]+>/g,' ').replace(/&nbsp;|&#160;/g,' ').replace(/\s+/g,' ');const spread=chunk.match(/Point Spread:\s*Seahawks\s*([+-]?\d+(?:\.\d+)?)/i),ml=chunk.match(/Moneyline:\s*Seahawks\s*([+-]?\d+)\s*\/\s*Titans\s*([+-]?\d+)/i),total=chunk.match(/Over\/Under:\s*([0-9]+(?:\.\d+)?)/i);if(!spread||!ml||!total)throw new Error('Published Titans line could not be parsed');return busrRows({spread:Number(spread[1]),seahawksMl:Number(ml[1]),titansMl:Number(ml[2]),total:Number(total[1]),capturedAt:new Date().toISOString()});}
function referenceExpired(){return Date.now()>=new Date(KICKOFF).getTime()}
export default async function handler(req,res){
  if(req.method!=='GET'){res.setHeader('Allow','GET');return res.status(405).json({ok:false,error:'Method not allowed'})}
  res.setHeader('Cache-Control','public, s-maxage=180, stale-while-revalidate=600');const diagnostics=[];
  try{const configured=await fetchFreeOdds(process.env,{maxEvents:3});if(configured.ok&&(configured.odds?.length||configured.events?.length))return res.status(200).json({...configured,propsAvailable:true,sourceMode:'configured-provider',quality:'live-provider',message:'Live configured provider data.',diagnostics});}catch(e){diagnostics.push(`Configured provider: ${e.message}`)}
  try{const parsed=spreadRows(await json(SPREAD_URL));if(parsed.odds.length)return res.status(200).json({ok:true,provider:'TheSpread.io keyless feed',events:parsed.events,odds:parsed.odds,futures:[],propsAvailable:false,sourceMode:'keyless-live',quality:'live-keyless',message:'Keyless game-line feed loaded. Player props require a configured props provider.',diagnostics,fetchedAt:new Date().toISOString()});diagnostics.push('TheSpread.io returned no current Titans rows.');}catch(e){diagnostics.push(`TheSpread.io: ${e.message}`)}
  if(!referenceExpired()){
    try{const ref=await busrPublishedReference();return res.status(200).json({ok:true,provider:'BUSR Week 2 published lines',events:ref.events,odds:ref.odds,futures:[],propsAvailable:false,sourceMode:'published-reference',quality:'published-reference',message:'No live feed is reachable, so the board is showing a dated published Week 2 market reference instead of failing.',diagnostics,referenceNotice:'Published Aug. 18 market article — not a live sportsbook feed. Refresh retries live providers first. Verify a current sportsbook before relying on a line.',referencePublishedAt:'2026-08-18T00:00:00Z',referenceExpiresAt:KICKOFF,sources:[{label:'BUSR · Aug. 18 Week 2 market article',url:BUSR_URL},{label:'NFL official Titans schedule',url:NFL_SCHEDULE}],fetchedAt:new Date().toISOString()});}catch(e){diagnostics.push(`BUSR published reference: ${e.message}`)}
    const ref=busrRows();return res.status(200).json({ok:true,provider:'Audited Aug. 18 published reference',events:ref.events,odds:ref.odds,futures:[],propsAvailable:false,sourceMode:'audited-reference',quality:'published-reference',message:'Live providers are unavailable. This is the audited Aug. 18 published Week 2 reference, preserved so the section stays useful without pretending the line is live.',diagnostics,referenceNotice:'Dated published reference — SEA -2.5 / -140, TEN +2.5 / +120, total 37.5. It is not guaranteed current and automatically disappears at kickoff.',referencePublishedAt:'2026-08-18T00:00:00Z',referenceExpiresAt:KICKOFF,sources:[{label:'BUSR · Aug. 18 Week 2 market article',url:BUSR_URL},{label:'NFL official Titans schedule',url:NFL_SCHEDULE}],fetchedAt:new Date().toISOString()});
  }
  return res.status(200).json({ok:true,provider:'No verified current market source',events:[],odds:[],futures:[],propsAvailable:false,sourceMode:'no-current-source',quality:'unavailable',message:'The dated preseason reference has expired and no live provider is currently reachable. No stale odds are shown.',diagnostics,fetchedAt:new Date().toISOString()});
}
